FROM python:3.11-slim
ARG PRJ_PATH
WORKDIR /usr/noetl

RUN apt-get update && apt-get install -y \
    gcc \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

COPY  ${PRJ_PATH}/noetl/config.py \
      ${PRJ_PATH}/noetl/api.py \
      ${PRJ_PATH}/noetl/gql.py \
      ${PRJ_PATH}/noetl/natstream.py \
      ${PRJ_PATH}/noetl/record.py ./

COPY ${PRJ_PATH}/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt
RUN pip install spacy && python -m spacy download en_core_web_sm

EXPOSE 8021

CMD ["python", "./api.py"]
