apiVersion: noetl.io/v2
kind: Playbook
metadata:
  name: noetl_automation_main
  path: automation/main
  description: Main automation entry point for NoETL development workflows
workload:
  registry: "local"
  image_name: "noetl"
workflow:
  - step: route_target
    desc: Entry point - route to appropriate workflow based on target
    tool:
      kind: shell
      cmds:
        - echo "Target is '{{ target }}'"
    spec:
      next_mode: exclusive
    next:
      - step: show_help
        when: "{{ target == 'help' }}"
      - step: bootstrap
        when: "{{ target == 'bootstrap' }}"
      - step: bootstrap
        when: "{{ target == 'boot' }}"
      - step: destroy
        when: "{{ target == 'destroy' }}"
      - step: quick_dev
        when: "{{ target == 'dev' }}"
      - step: unknown_target

  - step: show_help
    desc: Display available automation targets
    tool:
      kind: shell
      cmds:
        - |
          echo "====================================="
          echo " NoETL Automation Playbooks"
          echo "====================================="
          echo ""
          echo "Usage:"
          echo "  noetl run boot        (or: noetl run bootstrap)"
          echo "  noetl run destroy"
          echo "  noetl run dev"
          echo ""
          echo "Or with explicit paths:"
          echo "  noetl run automation/main.yaml --set target=bootstrap"
          echo "  noetl run automation/setup/bootstrap.yaml"
          echo ""
          echo "Available targets:"
          echo "  boot        - Complete K8s environment setup (alias: bootstrap)"
          echo "  destroy     - Destroy environment and clean up"
          echo "  dev         - Quick development cycle"
          echo "  help        - Show this help message"
          echo ""

  - step: bootstrap
    desc: Run complete bootstrap workflow
    tool:
      kind: playbook
      path: automation/setup/bootstrap.yaml

  - step: destroy
    desc: Run destroy workflow
    tool:
      kind: playbook
      path: automation/setup/destroy.yaml

  - step: quick_dev
    desc: Quick development cycle
    tool:
      kind: shell
      cmds:
        - echo "Quick dev workflow not yet implemented"

  - step: unknown_target
    desc: Handle unknown target
    tool:
      kind: shell
      cmds:
        - |
          echo "Error: Unknown target '{{ target }}'"
          echo "Available targets: bootstrap, destroy, dev, help"
          exit 1
