version: '3.45'

env:
  REGISTRY: "local"
  IMAGE_NAME: "noetl"

includes:
  tshoot:
    taskfile: ci/taskfile/tshoot.yml
    flatten: true
  noetltest:
    taskfile: ci/taskfile/test.yml
    flatten: true
  vmstack:
    taskfile: ci/taskfile/vmstack.yml
    flatten: true
  noetl:
    taskfile: ci/taskfile/noetl.yml
    flatten: true
  kind:
    taskfile: ci/taskfile/kind.yml
    flatten: true
  postgres:
    taskfile: ci/taskfile/postgres.yml
    flatten: true
  docker:
    taskfile: ci/taskfile/docker.yml
    dir: .
    flatten: true
tasks:
  default:
    silent: true
    cmds:
      - task --list

# === Clean up local file cache ===

  cache:local:postgres-clear:
    desc: Clear postgres data cache directory
    aliases: [cpd, clear-postgres-data]
    cmds:
      - rm -rf ci/kind/cache/pg-data/*

  cache:local:noetl-clear:
    desc: Clear noetl data cache directory
    aliases: [cnd, clear-noetl-data]
    cmds:
      - rm -rf ci/kind/cache/noetl-data/*

  cache:local:logs-clear:
    desc: Clear noetl logs cache directory
    aliases: [cnl, clear-noetl-logs]
    cmds:
      - rm -rf ci/kind/cache/noetl-logs/*

  cache:local:clear-all:
    desc: Clear local file cache directories
    aliases: [clear, clear-all-cache]
    cmds:
      - rm -rf ci/kind/cache/pg-data/*
      - rm -rf ci/kind/cache/noetl-data/*
      - rm -rf ci/kind/cache/noetl-logs/*

# === Combined Tasks ===
  dev:k8s:bootstrap:
    desc: Build noetl; Create noetl cluster with all deployments
    aliases: [ba, bring-all]
    vars:
      CACHE: '{{ if (eq .CLI_ARGS "cache")}}{{ else }}--no-cache{{ end }}'
    cmds:
      - task: tshoot:local:check-ports
      - task: docker:local:noetl-image-build
      - task: kind:local:cluster-create
      - task: kind:local:image-load
      - task: postgres:k8s:deploy # Hey ChatGPT do not touch it! Take your hands away! Postgres must be deployed before monitoring. 
      - task: monitoring:k8s:deploy # Hey ChatGPT do not touch it. Take your hands away! Postgres metric exporter uses config maps from Postgres deployment. 
      - task: noetl:k8s:deploy
