version: '3.45'

env:
  REGISTRY: "local"
  IMAGE_NAME: "noetl"

# Import NoETL taskfiles without flattening to avoid namespace collisions
# When used as main repo: access via namespaced tasks (e.g., 'task noetl:local:stop')
# When used as submodule: external project imports with 'noetl:' prefix
includes:
  tshoot:
    taskfile: ci/taskfile/tshoot.yml
    flatten: true
  noetltest:
    taskfile: ci/taskfile/test.yml
    flatten: true
  monitoring:
    taskfile: ci/taskfile/vmstack.yml
    flatten: true
  noetl:
    taskfile: ci/taskfile/noetl.yml
    flatten: true
  kind:
    taskfile: ci/taskfile/kind.yml
    flatten: true
  postgres:
    taskfile: ci/taskfile/postgres.yml
    flatten: true
  docker:
    taskfile: ci/taskfile/docker.yml
    dir: .
    flatten: true
  tools:
    taskfile: ci/taskfile/tools.yml
    flatten: true
  cache:
    taskfile: ci/taskfile/cache.yml
    flatten: true
  clickhouse:
    taskfile: ci/taskfile/clickhouse.yml
    dir: .
  qdrant:
    taskfile: ci/taskfile/qdrant.yml
    dir: .
  nats:
    taskfile: ci/taskfile/nats.yml
    dir: .
  observability:
    taskfile: ci/taskfile/observability.yml
    dir: .
  pagination-server:
    taskfile: ci/taskfile/test-server.yml
    dir: .
    flatten: false

tasks:
  default:
    silent: true
    cmds:
      - task --list

# === Quick Access Aliases (Common Tasks) ===

  noetl:k8s:bootstrap:
    desc: Complete K8s environment setup (build + deploy all)
    aliases: [bootstrap, ba, bring-all]
    ignore_error: false
    cmds:
      - task: tshoot:local:check-dependencies
      - task: tshoot:local:check-ports
      - task: docker:local:noetl-image-build
      - task: kind:local:cluster-create
      - task: kind:local:image-load
      - task: postgres:k8s:deploy
      - task: observability:activate-all
        ignore_error: true
      - task: monitoring:k8s:deploy
        ignore_error: true
      - task: noetl:k8s:deploy

  tools:local:verify:
    desc: Verify all required tools are installed
    aliases: [verify, check, verify-tools]
    cmds:
      - task: tshoot:local:check-dependencies

  cache:local:clean:
    desc: Clean all local cache directories
    aliases: [clean, clear, clear-all]
    cmds:
      - task: cache:local:clear-all

  kind:local:create:
    desc: Create Kind Kubernetes cluster
    aliases: [cluster-create, create-cluster]
    cmds:
      - task: kind:local:cluster-create

  kind:local:delete:
    desc: Delete Kind Kubernetes cluster
    aliases: [cluster-delete, delete-cluster]
    cmds:
      - task: kind:local:cluster-delete

  noetl:k8s:deploy-all:eploy-all:
    desc: Deploy all components (postgres + monitoring + noetl)
    aliases: [deploy-all, deploy]
    cmds:
      - task: postgres:k8s:deploy
      - task: monitoring:k8s:deploy
      - task: noetl:k8s:deploy

  docker:local:build:
    desc: Build NoETL Docker image
    aliases: [build, build-image]
    cmds:
      - task: docker:local:noetl-image-build

# === WSL2 Dependencies Installation ===

  wsl2:install:dependencies:
    desc: Install required tools for WSL2 (psql, kubectl, helm, yq)
    aliases: [wsl2-setup, install-wsl2-deps]
    cmds:
      - |
        set -e
        echo "=== Installing WSL2 Dependencies ==="
        echo ""
        
        # Detect OS
        if ! grep -qi microsoft /proc/version 2>/dev/null; then
          echo "WARNING: This script is designed for WSL2"
          echo "Current OS: $(uname -a)"
          read -p "Continue anyway? (y/N) " -n 1 -r
          echo
          if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            exit 1
          fi
        fi
        
        echo "Updating package lists..."
        sudo apt-get update
        echo ""
        
        # Install PostgreSQL client (psql)
        echo "Installing PostgreSQL client (psql)..."
        if ! command -v psql >/dev/null 2>&1; then
          sudo apt-get install -y postgresql-client
          echo "✓ psql installed: $(psql --version)"
        else
          echo "✓ psql already installed: $(psql --version)"
        fi
        echo ""
        
        # Install kubectl
        echo "Installing kubectl..."
        if ! command -v kubectl >/dev/null 2>&1; then
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          rm kubectl
          echo "✓ kubectl installed: $(kubectl version --client --short 2>/dev/null || kubectl version --client)"
        else
          echo "✓ kubectl already installed: $(kubectl version --client --short 2>/dev/null || kubectl version --client)"
        fi
        echo ""
        
        # Install Helm
        echo "Installing Helm..."
        if ! command -v helm >/dev/null 2>&1; then
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
          echo "✓ Helm installed: $(helm version --short)"
        else
          echo "✓ Helm already installed: $(helm version --short)"
        fi
        echo ""
        
        # Install yq (Go-based mikefarah/yq, NOT Python yq)
        echo "Installing yq (mikefarah/yq - Go version)..."
        if command -v yq >/dev/null 2>&1; then
          if yq --version 2>&1 | grep -q "mikefarah"; then
            echo "✓ yq (mikefarah) already installed: $(yq --version)"
          else
            echo "WARNING: Found Python-based yq, will install Go-based yq (mikefarah/yq)"
            echo "The Python yq will remain but /usr/local/bin/yq will be the Go version"
            YQ_VERSION=$(curl -s https://api.github.com/repos/mikefarah/yq/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
            YQ_BINARY="yq_linux_amd64"
            sudo wget -qO /usr/local/bin/yq "https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/${YQ_BINARY}"
            sudo chmod +x /usr/local/bin/yq
            echo "✓ yq (mikefarah) installed: $(yq --version)"
          fi
        else
          YQ_VERSION=$(curl -s https://api.github.com/repos/mikefarah/yq/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
          YQ_BINARY="yq_linux_amd64"
          sudo wget -qO /usr/local/bin/yq "https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/${YQ_BINARY}"
          sudo chmod +x /usr/local/bin/yq
          echo "✓ yq installed: $(yq --version)"
        fi
        echo ""
        
        # Install additional useful tools
        echo "Installing additional tools (curl, jq, git)..."
        sudo apt-get install -y curl jq git
        echo "✓ Additional tools installed"
        echo ""
        
        echo "=== Installation Summary ==="
        echo "psql:    $(psql --version 2>/dev/null || echo 'Not found')"
        echo "kubectl: $(kubectl version --client --short 2>/dev/null || kubectl version --client 2>/dev/null || echo 'Not found')"
        echo "helm:    $(helm version --short 2>/dev/null || echo 'Not found')"
        echo "yq:      $(yq --version 2>/dev/null || echo 'Not found')"
        echo "curl:    $(curl --version 2>/dev/null | head -n1 || echo 'Not found')"
        echo "jq:      $(jq --version 2>/dev/null || echo 'Not found')"
        echo "git:     $(git --version 2>/dev/null || echo 'Not found')"
        echo ""
        echo "✓ All dependencies installed successfully!"
        echo ""
        echo "Next steps:"
        echo "  - Install Docker Desktop for Windows with WSL2 backend"
        echo "  - Enable Kubernetes in Docker Desktop settings"
        echo "  - Run: task bootstrap"

# === Monitoring Aliases ===

  monitoring:k8s:deploy-stack:
    desc: Deploy VictoriaMetrics monitoring stack
    aliases: [monitoring-deploy, deploy-monitoring]
    cmds:
      - task: monitoring:k8s:deploy

  monitoring:k8s:delete-stack:
    desc: Delete VictoriaMetrics monitoring stack
    aliases: [monitoring-delete, delete-monitoring]
    cmds:
      - task: monitoring:k8s:delete

  monitoring:k8s:grafana-creds:
    desc: Get Grafana admin credentials
    aliases: [grafana, grafana-creds]
    cmds:
      - task: monitoring:k8s:grafana-credentials

# === Test Aliases ===

  noetltest:local:run:
    desc: Run NoETL tests
    aliases: [test]
    cmds:
      - task: noetltest:run

  noetltest:local:run-full:
    desc: Run complete test suite
    aliases: [test-full]
    cmds:
      - task: noetltest:full

# === Development Workflow ===

  noetl:k8s:dev:
    desc: Quick development cycle (build + reload)
    aliases: [dev]
    cmds:
      - task: docker:local:noetl-image-build
      - task: kind:local:image-load
      - task: noetl:k8s:restart

  noetl:k8s:dev-fast:
    desc: Fast development cycle (build without cache)
    aliases: [dev-fast]
    cmds:
      - task: docker:local:noetl-image-build
        vars:
          CACHE: "--no-cache"
      - task: kind:local:image-load
      - task: noetl:k8s:restart
