version: '3.45'

env:
  REGISTRY: "local"
  IMAGE_NAME: "noetl"

tasks:
  default:
    silent: true
    cmds:
      - task --list

  install-kind:
    desc: Install kind.sigs.k8s.io
    aliases: [install-kind]
    cmds:
      - brew install kind

# === Kind Kubernetes Cluster ===
  kind-create-cluster:
    desc: Create noetl kind cluster
    aliases: [kcc]
    cmds:
      - kind create cluster --config=ci/kind/config.yaml

  kind-delete-cluster:
    desc: Delete noetl kind cluster
    aliases: [kdc]
    cmds:
      - kind delete cluster --name=noetl

  kind-get-clustes:
    desc: Show all kind clusters
    aliases: [kgc]
    cmds:
      - kind get clusters

  kubectl-set-context-kind:
    desc: Set kubectl context to kind-noetl cluster
    aliases: [ksck]
    cmds:
      - kubectl config use-context kind-noetl

# === Postgres ===
  deploy-postgres:
    desc: Deploy postgres to the noetl kind cluster
    aliases: [dp]
    cmds:
      - kubectl config use-context kind-noetl
      - kubectl apply -f ci/manifests/postgres/namespace.yaml
      - sleep 2
      - kubectl apply -f ci/manifests/postgres/

  remove-postgres:
    desc: Remove postgres from the noetl kind cluster
    aliases: [rp]
    cmds:
      - kubectl config use-context kind-noetl
      - kubectl delete -f ci/manifests/postgres/

  clear-postgres-data:
    desc: Clear postgres pgdata folder on the host
    aliases: [cpd]
    cmds:
      - rm -rf ci/kind/data/*

# === NOETL ===
  docker-build-noetl:
    desc: Build the noetl container with dynamic tag
    aliases: [dbn]
    env:
      IMAGE_TAG:
        sh: date +%Y-%m-%d-%H-%M
    # The platform is not specified intentionally. The image platform should match the kind platform.
    cmds:
      - |
        echo $IMAGE_TAG > .noetl_last_build_tag.txt
        docker build --progress plain -t $REGISTRY/$IMAGE_NAME:$IMAGE_TAG -f docker/noetl/dev/Dockerfile .

  load-noetl-image:
    desc: Load noetl image to the noetl kind cluster
    aliases: [lni]
    env:
      IMAGE_TAG:
        sh: cat .noetl_last_build_tag.txt
    cmds:
      - kind load docker-image $REGISTRY/$IMAGE_NAME:$IMAGE_TAG --name noetl

  show-kind-images:
    desc: Show images inside of the noetl kind cluster
    aliases: [ski]
    cmds:
      - docker exec -it noetl-control-plane crictl images

  deploy-noetl:
    desc: Deploy noetl to the noetl kind cluster
    aliases: [dn]
    env:
      IMAGE_TAG:
        sh: cat .noetl_last_build_tag.txt
    cmds:
      - kubectl config use-context kind-noetl
      - kubectl apply -f ci/manifests/noetl/namespace.yaml
      - sleep 2
      - yq -i ".spec.template.spec.containers[0].image = \"$REGISTRY/$IMAGE_NAME:$IMAGE_TAG\"" ci/manifests/noetl/srv-deployment.yaml
      # - yq -i ".spec.template.spec.containers[0].image = \"$REGISTRY/$IMAGE_NAME:$IMAGE_TAG\"" ci/manifests/noetl/wrk-deployment.yaml
      - kubectl apply -f ci/manifests/noetl/
      - yq -i ".spec.template.spec.containers[0].image = \"image_name:image_tag\"" ci/manifests/noetl/srv-deployment.yaml
      # - yq -i ".spec.template.spec.containers[0].image = \"image_name:image_tag\"" ci/manifests/noetl/wrk-deployment.yaml

  remove-noetl:
    desc: Remove noetl from the noetl kind cluster
    aliases: [rn]
    cmds:
      - kubectl config use-context kind-noetl
      - kubectl delete -f ci/manifests/noetl/

  clear-docker-images:
    desc: Clear all {{ .REGISTRY }}/{{ .IMAGE_NAME }} docker images
    aliases: [cdi]
    cmds:
      - docker images "{{ .REGISTRY }}/{{ .IMAGE_NAME }}" --format "{{`{{.ID}}`}}" | xargs -r docker rmi -f

# === Combined Tasks ===
  bring-up-kind:
    desc: Build noetl; Create noetl cluster; Deploy postgres, noetl
    aliases: [buk]
    cmds:
      - task: docker-build-noetl
      - task: kind-create-cluster
      - task: load-noetl-image
      - task: deploy-postgres
      - task: deploy-noetl

  clean-up-kind-postgres-data:
    desc: Destroy noetl cluster; Remove postgres host data
    aliases: [cln]
    cmds:
      - task: kind-delete-cluster
      - task: clear-postgres-data

  recreate-kind-with-workload:
    desc: Rebuild noetl; Recreate noetl kind cluster; Redeploy postgres, noetl
    aliases: [rkw]
    cmds:
      - task: kind-delete-cluster
      - task: docker-build-noetl
      - task: kind-create-cluster
      - task: load-noetl-image
      - task: deploy-postgres
      - task: deploy-noetl
