apiVersion: noetl.io/v1
kind: Playbook
metadata:
  name: test_data_transition_fix
  path: test/data_transition_fix
workload:
  message: "Hello from workload"
workflow:
  - step: start
    desc: "Start test - pass data via next transition"
    next:
      - step: test_step
        data:
          message: "{{ workload.message }}"
          extra: "Additional data from transition"

  - step: test_step
    desc: "Test step that should receive the data"
    type: python
    code: |
      def main(message, extra):
          print(f"SUCCESS: Received message='{message}' and extra='{extra}'")
          return {
              "status": "success", 
              "data": {
                "received_message": message,
                "received_extra": extra,
                "test_passed": True
              }
          }
    next:
      - step: end

  - step: end
    desc: "End test"
    result:
      test_result: "{{ test_step.test_passed }}"
      message_received: "{{ test_step.received_message }}"
      extra_received: "{{ test_step.received_extra }}"