apiVersion: noetl.io/v1
kind: Playbook
metadata:
  name: test_retry_fail_http
  path: tests/retry/fail_http
  description: Test retry with HTTP 500 error

workload:
  test_url: https://httpstat.us/500
  
workflow:
  - step: start
    desc: Entry point - route to HTTP call
    next:
      - http_call
  
  - step: http_call
    desc: HTTP call that returns 500
    type: http
    method: GET
    url: "{{ workload.test_url }}"
    retry:
      max_attempts: 5
      initial_delay: 2.0
      backoff_multiplier: 1.5
      max_delay: 10.0
      jitter: false
      # Retry on 5xx errors
      retry_when: "{{ status_code >= 500 }}"
    next:
      - end
        
  - step: end
    desc: End of workflow
