apiVersion: noetl.io/v1
kind: Playbook
metadata:
  name: test-target-query
  path: /test/snowflake-transfer/target-query

workload:
  test_mode: false

workflow:
  - step: transfer
    desc: Test target.query parameter with custom INSERT
    type: snowflake_transfer
    direction: sf_to_pg
    source:
      query: |
        SELECT 
          'test_id' as id,
          'test_name' as name,
          100 as amount
    target:
      # Using target.query instead of target.table
      query: |
        INSERT INTO test_custom_target (id, name, amount)
        VALUES (%s, %s, %s)
        ON CONFLICT (id) DO UPDATE SET
          name = EXCLUDED.name,
          amount = EXCLUDED.amount
    chunk_size: 1000
    credential: snowflake_dev
    credentials:
      target:
        key: postgres_local
    next:
      - step: end

  - step: end
    desc: Complete test
