apiVersion: noetl.io/v1
kind: Playbook
metadata:
  name: test_retry_always_fail_events
  path: tests/retry/always_fail_events
  description: Test retry with guaranteed failure to verify retry events

workload:
  test_value: 1
  
workflow:
  - step: start
    desc: Entry point - route to failing task
    next:
      - failing_task
  
  - step: failing_task
    desc: Python code that always fails
    type: python
    code: |
      def main(input_data):
          # This will ALWAYS fail to test retry and event emission
          raise Exception("Intentional failure for retry event testing")
    retry:
      max_attempts: 3
      initial_delay: 1.0
      backoff_multiplier: 1.5
      max_delay: 5.0
      jitter: false
      # Retry on any error
      retry_when: "{{ error != None }}"
    next:
      - end
        
  - step: end
    desc: End workflow
