apiVersion: noetl.io/v1
kind: Playbook
name: city_process
path: examples/weather/city_process

workload:
  # Input parameters - these will be provided by the calling playbook
  city:
    name: ""
    lat: 0
    lon: 0
  base_url: ""
  temperature_threshold: 0

workflow:
  - step: start
    desc: "Start city processing"
    next:
      - step: get_forecast_step
        with:
          city: "{{ workload.city }}"
          base_url: "{{ workload.base_url }}"

  - step: get_forecast_step
    desc: "Fetch forecast for one city"
    type: python
    code: |
      def main(**kwargs):
          print(f"GET_FORECAST_STEP: Received kwargs: {kwargs}")
          print(f"GET_FORECAST_STEP: Workload: {kwargs.get('workload', 'MISSING')}")
          # Return empty forecast data for now
          return {}
    next:
      - step: evaluate_weather_step

  - step: evaluate_weather_step
    desc: "Evaluate weather using fetched forecast"
    type: workbook
    task: evaluate_weather
    with:
      city: "{{ workload.city }}"
      threshold: "{{ workload.temperature_threshold }}"
      forecast_data: "{{ get_forecast_step }}"
    next:
      - step: decide

  - step: decide
    desc: "Decide alert vs log"
    type: python
    code: |
      def main(city, result):
          print(f"DECIDE_STEP: Received city: {city}")
          print(f"DECIDE_STEP: Received result: {result}")
          if isinstance(result, dict) and result.get("alert"):
              decision = {"action": "alert", "city": city.get("name") if isinstance(city, dict) else city, "max_temp": result.get("max_temp", 0)}
          else:
              decision = {"action": "log", "city": city.get("name") if isinstance(city, dict) else city}
          print(f"DECIDE_STEP: Decision: {decision}")
          return decision
    with:
      city: "{{ workload.city }}"
      result: "{{ evaluate_weather_step }}"
    next:
      - when: "{{ decide.action == 'alert' }}"
        then:
          - step: alert_step
            with:
              city: "{{ workload.city.name }}"
              max_temp: "{{ decide.max_temp }}"
      - else:
          - step: log_step
            with:
              city: "{{ workload.city.name }}"

  - step: alert_step
    desc: "Send alert if threshold exceeded"
    type: python
    code: |
      def main(city, temperature, evaluation_result):
          # Note: This would call the alert_task workbook task
          # For now, just return the alert info
          result = {
              "action": "alert", 
              "city": city, 
              "temperature": temperature,
              "max_temp": evaluation_result.get("max_temp", 0),
              "alert": True
          }
          print(f"ALERT_STEP: Returning result: {result}")
          return result
    with:
      city: "{{ workload.city.name }}"
      temperature: "{{ decide.max_temp }}"
      evaluation_result: "{{ evaluate_weather_step }}"
    next:
      - step: end

  - step: log_step
    desc: "Log result if no alert"
    type: python
    code: |
      def main(city, evaluation_result):
          # Note: This would call the log_task workbook task
          # For now, just return the log info
          result = {
              "action": "log", 
              "city": city,
              "max_temp": evaluation_result.get("max_temp", 0),
              "alert": False
          }
          print(f"LOG_STEP: Returning result: {result}")
          return result
    with:
      city: "{{ workload.city.name }}"
      evaluation_result: "{{ evaluate_weather_step }}"
    next:
      - step: end

  - step: end
    desc: "End of city processing"
    return: "evaluate_weather"  # Return the result from the evaluate_weather step (system renames evaluate_weather_step)

workbook:
  # - name: get_forecast
  #   type: http
  #   method: GET
  #   endpoint: "{{ base_url }}/forecast"
  #   params:
  #     latitude: "{{ city.lat }}"
  #     longitude: "{{ city.lon }}"
  #     hourly: "temperature_2m"
  #     forecast_days: 1

  - name: evaluate_weather
    type: python
    with:
      city: "{{ city }}"
      threshold: "{{ threshold }}"
      forecast_data: "{{ forecast_data }}"
    code: |
      def main(city, threshold, forecast_data):
          try:
              threshold = float(threshold) if threshold not in (None, "") else 25.0
          except Exception:
              threshold = 25.0

          temps = []
          if isinstance(forecast_data, dict):
              hourly = forecast_data.get("hourly", {})
              if isinstance(hourly, dict):
                  temps = hourly.get("temperature_2m", []) or []

          max_temp = max(temps) if temps else 0.0
          return {"city": city.get("name"), "max_temp": max_temp, "alert": bool(max_temp > threshold)}

  - name: alert_task
    type: http
    method: POST
    endpoint: "https://postman-echo.com/post"
    payload:
      kind: "city_alert"
      city: "{{ city }}"
      temperature: "{{ temperature }}"
      message: "High temperature alert."
    timeout: 10

  - name: log_task
    type: http
    method: POST
    endpoint: "https://postman-echo.com/post"
    payload:
      kind: "city_log"
      city: "{{ city }}"
      message: "No alert needed."
    timeout: 10
