apiVersion: workflow.example.com/v1
kind: Workflow
metadata:
  name: main_workflow

spec:
  # Define the schedule for the workflow
  schedule: "*/5 * * * *"

  # Define variables for the workflow
  variables:
    default_timeout: 60

  initial_state: ready
  transitions:
    ready: [running]
    running: [idle, completed, failed]
    idle: [ready, running]
  conditions:
    - "'{{spec.variables.example_workflow.status}}' == 'ready'"

  jobs:
    - name: job1           # Name of the job
      runtime: docker      # Runtime for the job (e.g., 'docker')
      tasks:
        - name: task1      # Name of the task
          kind: shell      # Type of task (e.g., 'shell')
          command: "python run_workflow.py workflow_1.yaml"   # Command to execute for the task
          timeout: "{{main_workflow.variables.default_timeout}}"  # Timeout for the task
        - name: task2      # Name of another task
          kind: shell      # Type of task (e.g., 'shell')
          command: "python run_workflow.py workflow_2.yaml"   # Command to execute for the task
          timeout: "{{main_workflow.variables.default_timeout}}"  # Timeout for the task
