apiVersion: workflow.noetl.io/v1
kind: Workflow
metadata:
  name: example_workflow
spec:
  schedule: "*/5 * * * *"
  variables:
    default_timeout: 60
  initial_state: ready
  transitions:
    ready: [running]
    running: [idle, completed, failed]
    idle: [ready, running]
  conditions:
    - "'{{workflow.variables.example_workflow.status}}' == 'ready'"
  jobs:
    - name: job1
      runtime: docker
      conditions:
        - "'{{example_workflow.jobs.job2.status}}' == 'success'"
      tasks:
        - name: task1
          conditions:
            - "'{{example_workflow.jobs.job1.tasks.task1.status}}' == 'success'"
          actions:
            - shell: "echo 'Hello, World 1'"
            - shell: "echo 'Hello, World 2'"
            - rest_api:
                method: GET
                url: "https://api.github.com/octocat"
                query: "{{example_workflow.jobs.job1.tasks.task1.output}}"

    - name: job2
      runtime: kubernetes
      schedule: "0 12 * * *"
      tasks:
        - name: task1
          actions:
            - shell: "echo 'Job2 Task1'"
