apiVersion: workflow.example.com/v1
kind: Workflow
metadata:
  name: example_workflow
spec:
  schedule: "*/5 * * * *"  # The cron expression format: '*/5 * * * *' represents every 5 minutes
  variables:
    default_timeout: 60
  initial_state: ready
  states: [ready, running, idle, completed, failed]
  transitions:
    - source: ready
      target: [running]
    - source: running
      target: [idle, completed, failed]
    - source: idle
      target: [ready, running]
  conditions:
    - "'{{workflow.variables.example_workflow.status}}' == 'ready'"
  jobs:
    - name: job1
      runtime: docker
      conditions:
        - "'{{example_workflow.jobs.job2.status}}' == 'success'"
      tasks:
        - name: task1
          kind: shell
          command: "echo 'Hello, World'"
          timeout: "{{example_workflow.variables.default_timeout}}"
          loop:
            - expr: "for k in range(0,10)"
        - name: task2
          kind: rest_api
          method: GET
          url: "https://api.github.com/octocat"
          loop:
            - expr: "for k in range(0,10)"
              query: "{{example_workflow.jobs.job1.tasks.task1.output}}"
          conditions:
            - "'{{example_workflow.jobs.job1.tasks.task1.status}}' == 'success'"

    - name: job2
      runtime: kubernetes
      schedule: "0 12 * * *"
      tasks:
        - name: task1
          kind: shell
          command: "echo 'Job2 Task1'"
          timeout: "{{example_workflow.variables.default_timeout}}"
