apiVersion: v1
items:
- apiVersion: v1
  kind: Namespace
  metadata:
    creationTimestamp: "2026-02-11T22:19:28Z"
    labels:
      kubernetes.io/metadata.name: default
    name: default
    resourceVersion: "1770848368660655001"
    uid: b933351e-5e9f-4c35-943c-16efca4ca415
  spec:
    finalizers:
    - kubernetes
  status:
    phase: Active
- apiVersion: v1
  kind: Namespace
  metadata:
    annotations:
      components.gke.io/component-name: managed-prometheus
      components.gke.io/component-version: 0.17.3-gke.0
      components.gke.io/layer: addon
    creationTimestamp: "2026-02-11T22:23:14Z"
    labels:
      addonmanager.kubernetes.io/mode: Reconcile
      kubernetes.io/metadata.name: gke-gmp-system
    name: gke-gmp-system
    resourceVersion: "1770848594020255021"
    uid: 5f4d95c7-1185-41ed-955b-ac18b75cb097
  spec:
    finalizers:
    - kubernetes
  status:
    phase: Active
- apiVersion: v1
  kind: Namespace
  metadata:
    annotations:
      components.gke.io/component-name: cluster-infra-metrics
      components.gke.io/component-version: 1.34.0-gke.0
      components.gke.io/layer: addon
    creationTimestamp: "2026-02-11T22:22:05Z"
    labels:
      addonmanager.kubernetes.io/mode: Reconcile
      kubernetes.io/metadata.name: gke-managed-cim
    name: gke-managed-cim
    resourceVersion: "1770848525625823001"
    uid: c275cefe-b1c8-4e31-b5f2-160a5d5b4014
  spec:
    finalizers:
    - kubernetes
  status:
    phase: Active
- apiVersion: v1
  kind: Namespace
  metadata:
    annotations:
      components.gke.io/component-name: filestorecsi
      components.gke.io/component-version: 1.34.10
      components.gke.io/layer: addon
    creationTimestamp: "2026-02-11T22:22:19Z"
    labels:
      addonmanager.kubernetes.io/mode: Reconcile
      k8s-app: gcp-filestore-csi-driver
      kubernetes.io/metadata.name: gke-managed-filestorecsi
    name: gke-managed-filestorecsi
    resourceVersion: "1770848539320239008"
    uid: 089ac256-d01e-4f0c-bd73-c801291542d0
  spec:
    finalizers:
    - kubernetes
  status:
    phase: Active
- apiVersion: v1
  kind: Namespace
  metadata:
    annotations:
      components.gke.io/component-name: parallelstorecsi
      components.gke.io/component-version: 1.34.7
      components.gke.io/layer: addon
    creationTimestamp: "2026-02-11T22:23:47Z"
    labels:
      addonmanager.kubernetes.io/mode: EnsureExists
      k8s-app: parallelstore-csi-driver
      kubernetes.io/metadata.name: gke-managed-parallelstorecsi
    name: gke-managed-parallelstorecsi
    resourceVersion: "1770848627613375023"
    uid: 07da8b9c-d772-4119-b2fd-a09635242150
  spec:
    finalizers:
    - kubernetes
  status:
    phase: Active
- apiVersion: v1
  kind: Namespace
  metadata:
    annotations:
      components.gke.io/component-name: gke-managed-system
      components.gke.io/component-version: 0.1.1
      components.gke.io/layer: addon
    creationTimestamp: "2026-02-11T22:22:42Z"
    labels:
      addonmanager.kubernetes.io/mode: Reconcile
      kubernetes.io/metadata.name: gke-managed-system
    name: gke-managed-system
    resourceVersion: "1770848562120127010"
    uid: 94735871-bc59-420b-a2fb-b46640dcc3fd
  spec:
    finalizers:
    - kubernetes
  status:
    phase: Active
- apiVersion: v1
  kind: Namespace
  metadata:
    annotations:
      components.gke.io/component-name: gke-volume-populator
      components.gke.io/component-version: 1.34.1
      components.gke.io/layer: addon
    creationTimestamp: "2026-02-11T22:22:54Z"
    labels:
      addonmanager.kubernetes.io/mode: Reconcile
      k8s-app: gke-volume-populator
      kubernetes.io/metadata.name: gke-managed-volumepopulator
    name: gke-managed-volumepopulator
    resourceVersion: "1770848574456575022"
    uid: 4a4d025f-d16e-4181-acde-8f439a281b7f
  spec:
    finalizers:
    - kubernetes
  status:
    phase: Active
- apiVersion: v1
  kind: Namespace
  metadata:
    annotations:
      components.gke.io/component-name: managed-prometheus
      components.gke.io/component-version: 0.17.3-gke.0
      components.gke.io/layer: addon
    creationTimestamp: "2026-02-11T22:23:14Z"
    labels:
      addonmanager.kubernetes.io/mode: Reconcile
      kubernetes.io/metadata.name: gmp-public
    name: gmp-public
    resourceVersion: "1770848594318415004"
    uid: 431425a5-e03c-47ca-973d-94eb7c9d9d10
  spec:
    finalizers:
    - kubernetes
  status:
    phase: Active
- apiVersion: v1
  kind: Namespace
  metadata:
    creationTimestamp: "2026-02-11T22:19:28Z"
    labels:
      kubernetes.io/metadata.name: kube-node-lease
    name: kube-node-lease
    resourceVersion: "1770848368831487003"
    uid: b6094787-09ce-4ddd-9bbc-c6e6a11f4c84
  spec:
    finalizers:
    - kubernetes
  status:
    phase: Active
- apiVersion: v1
  kind: Namespace
  metadata:
    creationTimestamp: "2026-02-11T22:19:28Z"
    labels:
      kubernetes.io/metadata.name: kube-public
    name: kube-public
    resourceVersion: "1770848368615567000"
    uid: e03a6eec-422f-4cde-b824-2bcc8b5a7c96
  spec:
    finalizers:
    - kubernetes
  status:
    phase: Active
- apiVersion: v1
  kind: Namespace
  metadata:
    creationTimestamp: "2026-02-11T22:19:28Z"
    labels:
      kubernetes.io/metadata.name: kube-system
    name: kube-system
    resourceVersion: "1770848368593663004"
    uid: 09cfb5c8-0a40-41b7-8cce-d93805e77422
  spec:
    finalizers:
    - kubernetes
  status:
    phase: Active
kind: List
metadata:
  resourceVersion: ""
