apiVersion: v1
kind: Secret
metadata:
  name: noetl-secret
  labels:
    app: noetl
type: Opaque
data:
  POSTGRES_PASSWORD: ZGVtbw==  # 'demo' encoded in base64
  NOETL_PASSWORD: bm9ldGw=    # 'noetl' encoded in base64