apiVersion: v1
kind: Service
metadata:
  name: noetl-ext
  namespace: noetl
  labels:
    app: noetl
spec:
  type: NodePort
  ports:
    - port: 8082
      nodePort: 30082
      protocol: TCP
      name: http
  selector:
    app: noetl
