apiVersion: v1
kind: Service
metadata:
  name: noetl
  namespace: noetl
  labels:
    app: noetl
spec:
  type: ClusterIP
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
      name: noetl
  selector:
    app: noetl
