apiVersion: noetl.io/v1
kind: Playbook
name: http_bearer_example
path: examples/credentials/http_bearer_example
version: 0.1.0
description: Demonstrate using stored bearer token credentials in an HTTP task

workflow:
  - step: start
    desc: "Start Workflow"
    next:
      - step: call_api
  - step: call_api
    type: workbook
    task: call_api_task
  - step: end

workbook:
  - name: call_api_task
    type: http
    method: GET
    endpoint: "https://httpbin.org/bearer"
    headers:
      Content-Type: application/json
    payload:
      message: "hello"
    authentication: genericCredentialType
    genericAuthType: httpBearerAuth
    credentials:
      httpBearerAuth:
        name: "my-bearer-token"  # Register this via POST /credentials {name:"my-bearer-token", type:"httpBearerAuth", data:{token:"..."}}
    timeout: 10
