apiVersion: noetl.io/v2
kind: Playbook
metadata:
  name: clickhouse_automation
  path: automation/infrastructure/clickhouse

workload:
  action: help  # deploy, undeploy, status, health, test, connect, query, logs, logs-operator, logs-mcp, port-forward, port-forward-mcp, restart, restart-operator, restart-mcp, clean-data, optimize, deploy-cluster, deploy-crds, deploy-namespace, deploy-operator, deploy-schema, deploy-grafana-datasource, deploy-mcp-server

workflow:
  - step: start
    desc: Entry point for ClickHouse automation
    tool:
      kind: shell
      cmds:
        - echo "ClickHouse Automation - Action '{{ action }}'"
    next:
      - when: "{{ action }} == deploy"
        then:
          - step: deploy_clickhouse
        args: {}
      - when: "{{ action }} == undeploy"
        then:
          - step: undeploy_clickhouse
        args: {}
      - when: "{{ action }} == status"
        then:
          - step: check_status
        args: {}
      - when: "{{ action }} == health"
        then:
          - step: check_health
        args: {}
      - when: "{{ action }} == test"
        then:
          - step: test_clickhouse
        args: {}
      - when: "{{ action }} == connect"
        then:
          - step: connect_cli
        args: {}
      - when: "{{ action }} == query"
        then:
          - step: execute_query
        args: {}
      - when: "{{ action }} == logs"
        then:
          - step: view_logs
        args: {}
      - when: "{{ action }} == logs-operator"
        then:
          - step: view_operator_logs
        args: {}
      - when: "{{ action }} == logs-mcp"
        then:
          - step: view_mcp_logs
        args: {}
      - when: "{{ action }} == port-forward"
        then:
          - step: port_forward
        args: {}
      - when: "{{ action }} == port-forward-mcp"
        then:
          - step: port_forward_mcp
        args: {}
      - when: "{{ action }} == restart"
        then:
          - step: restart_cluster
        args: {}
      - when: "{{ action }} == restart-operator"
        then:
          - step: restart_operator
        args: {}
      - when: "{{ action }} == restart-mcp"
        then:
          - step: restart_mcp
        args: {}
      - when: "{{ action }} == clean-data"
        then:
          - step: clean_data
        args: {}
      - when: "{{ action }} == optimize"
        then:
          - step: optimize_tables
        args: {}
      - when: "{{ action }} == deploy-cluster"
        then:
          - step: deploy_cluster
        args: {}
      - when: "{{ action }} == deploy-crds"
        then:
          - step: deploy_crds
        args: {}
      - when: "{{ action }} == deploy-namespace"
        then:
          - step: deploy_namespace
        args: {}
      - when: "{{ action }} == deploy-operator"
        then:
          - step: deploy_operator
        args: {}
      - when: "{{ action }} == deploy-schema"
        then:
          - step: deploy_schema
        args: {}
      - when: "{{ action }} == deploy-grafana-datasource"
        then:
          - step: deploy_grafana_datasource
        args: {}
      - when: "{{ action }} == deploy-mcp-server"
        then:
          - step: deploy_mcp_server
        args: {}
      - when: "{{ action }} == help"
        then:
          - step: show_help
        args: {}
      - step: show_help

  - step: deploy_clickhouse
    desc: Deploy complete ClickHouse observability stack
    tool:
      kind: shell
      cmds:
        - |
          echo ""
          echo "Deploying complete ClickHouse observability stack..."
          task clickhouse:deploy
    next:
      - step: end

  - step: undeploy_clickhouse
    desc: Remove ClickHouse observability stack
    tool:
      kind: shell
      cmds:
        - |
          echo ""
          echo "Removing ClickHouse observability stack..."
          task clickhouse:undeploy
    next:
      - step: end

  - step: check_status
    desc: Show ClickHouse stack status
    tool:
      kind: shell
      cmds:
        - |
          echo ""
          echo "ClickHouse Stack Status:"
          echo "========================"
          task clickhouse:status
    next:
      - step: end

  - step: check_health
    desc: Check ClickHouse cluster health
    tool:
      kind: shell
      cmds:
        - |
          echo ""
          echo "ClickHouse Cluster Health:"
          echo "=========================="
          task clickhouse:health
    next:
      - step: end

  - step: test_clickhouse
    desc: Test ClickHouse connection and schema
    tool:
      kind: shell
      cmds:
        - |
          echo ""
          echo "Testing ClickHouse connection and schema..."
          task clickhouse:test
    next:
      - step: end

  - step: connect_cli
    desc: Connect to ClickHouse CLI
    tool:
      kind: shell
      cmds:
        - |
          echo ""
          echo "Connecting to ClickHouse CLI..."
          task clickhouse:connect
    next:
      - step: end

  - step: execute_query
    desc: Execute ClickHouse query
    tool:
      kind: shell
      cmds:
        - |
          echo ""
          echo "Executing ClickHouse query..."
          task clickhouse:query
    next:
      - step: end

  - step: view_logs
    desc: Show ClickHouse server logs
    tool:
      kind: shell
      cmds:
        - |
          echo ""
          echo "ClickHouse Server Logs:"
          echo "======================="
          task clickhouse:logs
    next:
      - step: end

  - step: view_operator_logs
    desc: Show ClickHouse operator logs
    tool:
      kind: shell
      cmds:
        - |
          echo ""
          echo "ClickHouse Operator Logs:"
          echo "========================="
          task clickhouse:logs-operator
    next:
      - step: end

  - step: view_mcp_logs
    desc: Show ClickHouse MCP server logs
    tool:
      kind: shell
      cmds:
        - |
          echo ""
          echo "ClickHouse MCP Server Logs:"
          echo "==========================="
          task clickhouse:logs-mcp
    next:
      - step: end

  - step: port_forward
    desc: Forward ClickHouse ports
    tool:
      kind: shell
      cmds:
        - |
          echo ""
          echo "Forwarding ClickHouse ports..."
          echo "Press Ctrl+C to stop port-forwarding"
          task clickhouse:port-forward
    next:
      - step: end

  - step: port_forward_mcp
    desc: Forward ClickHouse MCP server port
    tool:
      kind: shell
      cmds:
        - |
          echo ""
          echo "Forwarding ClickHouse MCP server port..."
          echo "Press Ctrl+C to stop port-forwarding"
          task clickhouse:port-forward-mcp
    next:
      - step: end

  - step: restart_cluster
    desc: Restart ClickHouse cluster
    tool:
      kind: shell
      cmds:
        - |
          echo ""
          echo "Restarting ClickHouse cluster..."
          task clickhouse:restart
    next:
      - step: end

  - step: restart_operator
    desc: Restart ClickHouse operator
    tool:
      kind: shell
      cmds:
        - |
          echo ""
          echo "Restarting ClickHouse operator..."
          task clickhouse:restart-operator
    next:
      - step: end

  - step: restart_mcp
    desc: Restart ClickHouse MCP server
    tool:
      kind: shell
      cmds:
        - |
          echo ""
          echo "Restarting ClickHouse MCP server..."
          task clickhouse:restart-mcp
    next:
      - step: end

  - step: clean_data
    desc: Drop all observability data
    tool:
      kind: shell
      cmds:
        - |
          echo ""
          echo "Dropping all observability data..."
          echo "WARNING: This will delete all data!"
          task clickhouse:clean-data
    next:
      - step: end

  - step: optimize_tables
    desc: Optimize ClickHouse tables
    tool:
      kind: shell
      cmds:
        - |
          echo ""
          echo "Optimizing ClickHouse tables..."
          task clickhouse:optimize
    next:
      - step: end

  - step: deploy_cluster
    desc: Deploy ClickHouse cluster
    tool:
      kind: shell
      cmds:
        - |
          echo ""
          echo "Deploying ClickHouse cluster..."
          task clickhouse:deploy-cluster
    next:
      - step: end

  - step: deploy_crds
    desc: Deploy ClickHouse CRDs
    tool:
      kind: shell
      cmds:
        - |
          echo ""
          echo "Deploying ClickHouse CRDs..."
          task clickhouse:deploy-crds
    next:
      - step: end

  - step: deploy_namespace
    desc: Create ClickHouse namespace
    tool:
      kind: shell
      cmds:
        - |
          echo ""
          echo "Creating ClickHouse namespace..."
          task clickhouse:deploy-namespace
    next:
      - step: end

  - step: deploy_operator
    desc: Deploy ClickHouse operator
    tool:
      kind: shell
      cmds:
        - |
          echo ""
          echo "Deploying ClickHouse operator..."
          task clickhouse:deploy-operator
    next:
      - step: end

  - step: deploy_schema
    desc: Deploy observability schema to ClickHouse
    tool:
      kind: shell
      cmds:
        - |
          echo ""
          echo "Deploying observability schema..."
          task clickhouse:deploy-schema
    next:
      - step: end

  - step: deploy_grafana_datasource
    desc: Deploy ClickHouse datasource for Grafana
    tool:
      kind: shell
      cmds:
        - |
          echo ""
          echo "Deploying ClickHouse datasource for Grafana..."
          task clickhouse:deploy-grafana-datasource
    next:
      - step: end

  - step: deploy_mcp_server
    desc: Deploy ClickHouse MCP server
    tool:
      kind: shell
      cmds:
        - |
          echo ""
          echo "Deploying ClickHouse MCP server..."
          task clickhouse:deploy-mcp-server
    next:
      - step: end

  - step: show_help
    desc: Display available actions
    tool:
      kind: shell
      cmds:
        - |
          echo "=================================================="
          echo " ClickHouse Observability Stack Automation"
          echo "=================================================="
          echo ""
          echo "Usage:"
          echo "  noetl run automation/infrastructure/clickhouse.yaml --set action=<action>"
          echo ""
          echo "Main Actions:"
          echo "  deploy      - Deploy complete ClickHouse observability stack"
          echo "  undeploy    - Remove ClickHouse observability stack"
          echo "  status      - Show stack status"
          echo "  health      - Check cluster health"
          echo "  test        - Test connection and schema"
          echo ""
          echo "Granular Deployment:"
          echo "  deploy-namespace          - Create ClickHouse namespace"
          echo "  deploy-crds               - Deploy ClickHouse CRDs"
          echo "  deploy-operator           - Deploy ClickHouse operator"
          echo "  deploy-cluster            - Deploy ClickHouse cluster"
          echo "  deploy-schema             - Deploy observability schema"
          echo "  deploy-grafana-datasource - Deploy Grafana datasource"
          echo "  deploy-mcp-server         - Deploy MCP server"
          echo ""
          echo "Operations:"
          echo "  connect         - Connect to ClickHouse CLI"
          echo "  query           - Execute ClickHouse query"
          echo "  logs            - Show server logs"
          echo "  logs-operator   - Show operator logs"
          echo "  logs-mcp        - Show MCP server logs"
          echo "  port-forward    - Forward ClickHouse ports"
          echo "  port-forward-mcp - Forward MCP server port"
          echo ""
          echo "Management:"
          echo "  restart          - Restart ClickHouse cluster"
          echo "  restart-operator - Restart operator"
          echo "  restart-mcp      - Restart MCP server"
          echo "  clean-data       - Drop all observability data (WARNING!)"
          echo "  optimize         - Optimize ClickHouse tables"
          echo ""
          echo "Examples:"
          echo "  # Deploy complete stack"
          echo "  noetl run automation/infrastructure/clickhouse.yaml --set action=deploy"
          echo ""
          echo "  # Check status"
          echo "  noetl run automation/infrastructure/clickhouse.yaml --set action=status"
          echo ""
          echo "  # Connect to CLI"
          echo "  noetl run automation/infrastructure/clickhouse.yaml --set action=connect"
          echo ""
          echo "  # View logs"
          echo "  noetl run automation/infrastructure/clickhouse.yaml --set action=logs"
          echo ""
          echo "Task Equivalents:"
          echo "  deploy                    -> task clickhouse:deploy"
          echo "  undeploy                  -> task clickhouse:undeploy"
          echo "  status                    -> task clickhouse:status"
          echo "  health                    -> task clickhouse:health"
          echo "  test                      -> task clickhouse:test"
          echo "  connect                   -> task clickhouse:connect"
          echo "  query                     -> task clickhouse:query"
          echo "  logs                      -> task clickhouse:logs"
          echo "  logs-operator             -> task clickhouse:logs-operator"
          echo "  logs-mcp                  -> task clickhouse:logs-mcp"
          echo "  port-forward              -> task clickhouse:port-forward"
          echo "  port-forward-mcp          -> task clickhouse:port-forward-mcp"
          echo "  restart                   -> task clickhouse:restart"
          echo "  restart-operator          -> task clickhouse:restart-operator"
          echo "  restart-mcp               -> task clickhouse:restart-mcp"
          echo "  clean-data                -> task clickhouse:clean-data"
          echo "  optimize                  -> task clickhouse:optimize"
          echo "  deploy-cluster            -> task clickhouse:deploy-cluster"
          echo "  deploy-crds               -> task clickhouse:deploy-crds"
          echo "  deploy-namespace          -> task clickhouse:deploy-namespace"
          echo "  deploy-operator           -> task clickhouse:deploy-operator"
          echo "  deploy-schema             -> task clickhouse:deploy-schema"
          echo "  deploy-grafana-datasource -> task clickhouse:deploy-grafana-datasource"
          echo "  deploy-mcp-server         -> task clickhouse:deploy-mcp-server"
          echo ""
    next:
      - step: end

  - step: end
    desc: End workflow
