apiVersion: noetl.io/v2
kind: Playbook
metadata:
  name: gateway_automation
  path: automation/infrastructure/gateway

executor:
  profile: local
  version: noetl-runtime/1
workload:
  action: help  # build-image, load-image, deploy, deploy-all, remove, redeploy, restart, status, logs, test

workflow:
  - step: start
    desc: Entry point for Gateway automation
    tool:
      kind: shell
      cmds:
        - echo "Gateway Automation - Action '{{ workload.action }}'"
    next:
      - when: "{{ workload.action }} == build-image"
        then:
          - step: build_image
        args: {}
      - when: "{{ workload.action }} == load-image"
        then:
          - step: load_image
        args: {}
      - when: "{{ workload.action }} == deploy"
        then:
          - step: deploy_gateway
        args: {}
      - when: "{{ workload.action }} == deploy-all"
        then:
          - step: deploy_all
        args: {}
      - when: "{{ workload.action }} == remove"
        then:
          - step: remove_gateway
        args: {}
      - when: "{{ workload.action }} == redeploy"
        then:
          - step: redeploy_gateway
        args: {}
      - when: "{{ workload.action }} == restart"
        then:
          - step: restart_gateway
        args: {}
      - when: "{{ workload.action }} == status"
        then:
          - step: check_status
        args: {}
      - when: "{{ workload.action }} == logs"
        then:
          - step: view_logs
        args: {}
      - when: "{{ workload.action }} == test"
        then:
          - step: test_gateway
        args: {}
      - when: "{{ workload.action }} == help"
        then:
          - step: show_help
        args: {}
      - step: show_help

  - step: build_image
    desc: Build Gateway Docker image and load into kind
    tool:
      kind: shell
      cmds:
        - |
          echo ""
          echo "Building Gateway Docker image..."
          docker buildx build --load --platform linux/amd64 -t noetl-gateway:latest -f crates/gateway/Dockerfile crates/gateway
          echo "Loading Gateway image into kind cluster..."
          kind load docker-image noetl-gateway:latest --name noetl
          echo "Gateway image built and loaded into kind cluster"
    next:
      - step: end

  - step: load_image
    desc: Load Gateway image into kind cluster
    tool:
      kind: shell
      cmds:
        - |
          echo ""
          echo "Loading Gateway image into kind cluster..."
          if docker image inspect noetl-gateway:latest >/dev/null 2>&1; then
            kind load docker-image noetl-gateway:latest --name noetl
            echo "Gateway image loaded successfully"
          else
            echo "ERROR: noetl-gateway:latest image not found in Docker"
            echo "Build the image first with: noetl run automation/infrastructure/gateway.yaml --set action=build-image"
            exit 1
          fi
    next:
      - step: end

  - step: deploy_gateway
    desc: Deploy Gateway API to Kubernetes
    tool:
      kind: shell
      cmds:
        - |
          echo ""
          echo "Deploying Gateway API to Kubernetes..."
          kubectl apply -f ci/manifests/gateway/namespace.yaml
          kubectl apply -f ci/manifests/gateway/deployment.yaml
          kubectl apply -f ci/manifests/gateway/service.yaml
          echo "Gateway API deployed at http://localhost:8090"
    next:
      - step: end

  - step: deploy_all
    desc: Build and deploy Gateway API and UI to Kubernetes
    tool:
      kind: shell
      cmds:
        - |
          echo ""
          echo "Building and deploying Gateway API and UI..."
          docker buildx build --load --platform linux/amd64 -t noetl-gateway:latest -f crates/gateway/Dockerfile crates/gateway
          kind load docker-image noetl-gateway:latest --name noetl
          kubectl apply -f ci/manifests/gateway/namespace.yaml
          kubectl apply -f ci/manifests/gateway/deployment.yaml
          kubectl apply -f ci/manifests/gateway/service.yaml
          echo "Gateway API deployed at http://localhost:8090"
          kubectl apply -f ci/manifests/gateway/configmap-ui.yaml
          kubectl apply -f ci/manifests/gateway/configmap-ui-files.yaml
          kubectl apply -f ci/manifests/gateway/deployment-ui.yaml
          kubectl apply -f ci/manifests/gateway/service-ui.yaml
          echo "Gateway UI deployed at http://localhost:8080"
    next:
      - step: end

  - step: remove_gateway
    desc: Remove Gateway from Kubernetes
    tool:
      kind: shell
      cmds:
        - |
          echo ""
          echo "Removing Gateway from Kubernetes..."
          kubectl delete namespace gateway --ignore-not-found=true
    next:
      - step: end

  - step: redeploy_gateway
    desc: Rebuild and redeploy Gateway
    tool:
      kind: shell
      cmds:
        - echo ""
        - echo "Rebuilding Gateway image..."
        - docker buildx build --progress=plain --load --platform linux/amd64 -t noetl-gateway:latest -f crates/gateway/Dockerfile crates/gateway
        - echo "Loading into kind cluster..."
        - kind load docker-image noetl-gateway:latest --name noetl
        - echo "Restarting deployment..."
        - kubectl rollout restart deployment/gateway -n gateway
        - kubectl rollout status deployment/gateway -n gateway --timeout=60s
    next:
      - step: end

  - step: restart_gateway
    desc: Restart Gateway pods
    tool:
      kind: shell
      cmds:
        - |
          echo ""
          echo "Restarting Gateway pods..."
          kubectl rollout restart deployment/gateway -n gateway
          kubectl rollout restart deployment/gateway-ui -n gateway
    next:
      - step: end

  - step: check_status
    desc: Check Gateway deployment status
    tool:
      kind: shell
      cmds:
        - |
          echo ""
          echo "Gateway Deployment Status:"
          echo "=========================="
          kubectl get all -n gateway
    next:
      - step: end

  - step: view_logs
    desc: Show Gateway logs
    tool:
      kind: shell
      cmds:
        - |
          echo ""
          echo "Gateway Logs:"
          echo "============="
          kubectl logs -n gateway -l app=gateway --tail=100 -f
    next:
      - step: end

  - step: test_gateway
    desc: Test Gateway endpoints
    tool:
      kind: shell
      cmds:
        - |
          echo ""
          echo "Testing Gateway endpoints..."
          curl -s http://localhost:8090/graphql | head -20 || echo "Gateway not responding"
          curl -s http://localhost:8080/health || echo "Gateway UI not responding"
    next:
      - step: end

  - step: show_help
    desc: Display available actions
    tool:
      kind: shell
      cmds:
        - |
          echo "=================================================="
          echo " Gateway API Automation"
          echo "=================================================="
          echo ""
          echo "Usage:"
          echo "  noetl run automation/infrastructure/gateway.yaml --set action=<action>"
          echo ""
          echo "Build & Deployment:"
          echo "  build-image - Build Gateway Docker image and load into kind"
          echo "  build-image - Build Gateway Docker image and load into kind"
          echo "  load-image  - Load existing Gateway image into kind cluster"
          echo "  deploy      - Deploy Gateway API to Kubernetes"
          echo "  deploy-all  - Build and deploy Gateway API and UI"
          echo "  remove      - Remove Gateway from Kubernetes"
          echo "  redeploy    - Rebuild and redeploy Gateway"
          echo ""
          echo "Operations:"
          echo "  restart     - Restart Gateway pods"
          echo "  status      - Check deployment status"
          echo "  logs        - Show Gateway logs"
          echo "  test        - Test Gateway endpoints"
          echo ""
          echo "Examples:"
          echo "  # Build and deploy everything"
          echo "  noetl run automation/infrastructure/gateway.yaml --set action=deploy-all"
          echo ""
          echo "  # Check status"
          echo "  noetl run automation/infrastructure/gateway.yaml --set action=status"
          echo ""
          echo "  # Rebuild and redeploy"
          echo "  noetl run automation/infrastructure/gateway.yaml --set action=redeploy"
          echo ""
          echo "  # View logs"
          echo "  noetl run automation/infrastructure/gateway.yaml --set action=logs"
          echo ""
          echo "  # Test endpoints"
          echo "  noetl run automation/infrastructure/gateway.yaml --set action=test"
          echo ""
          echo "Gateway Location: crates/gateway"
          echo ""
    next:
      - step: end

  - step: end
    desc: End workflow
