apiVersion: noetl.io/v2
kind: Playbook
metadata:
  name: jupyterlab_automation
  path: automation/infrastructure/jupyterlab

executor:
  profile: local
  version: noetl-runtime/1
workload:
  action: help  # deploy, undeploy, full, status, logs, port-forward, restart, shell, test, update-notebook

workflow:
  - step: start
    desc: Entry point for JupyterLab automation
    tool:
      kind: shell
      cmds:
        - echo "JupyterLab Automation - Action '{{ workload.action }}'"
    next:
      spec:
        mode: exclusive
      arcs:
        - step: deploy_jupyterlab
          when: "{{ workload.action == 'deploy' }}"
        - step: undeploy_jupyterlab
          when: "{{ workload.action == 'undeploy' }}"
        - step: full_deployment
          when: "{{ workload.action == 'full' }}"
        - step: check_status
          when: "{{ workload.action == 'status' }}"
        - step: view_logs
          when: "{{ workload.action == 'logs' }}"
        - step: port_forward
          when: "{{ workload.action == 'port-forward' }}"
        - step: restart_deployment
          when: "{{ workload.action == 'restart' }}"
        - step: open_shell
          when: "{{ workload.action == 'shell' }}"
        - step: test_deployment
          when: "{{ workload.action == 'test' }}"
        - step: update_notebook
          when: "{{ workload.action == 'update-notebook' }}"
        - step: show_help
          when: "{{ workload.action == 'help' }}"
        - step: show_help

  - step: deploy_jupyterlab
    desc: Deploy JupyterLab to kind cluster
    tool:
      kind: shell
      cmds:
        - |
          echo ""
          echo "Deploying JupyterLab to noetl namespace..."
          kubectl create namespace noetl --dry-run=client -o yaml | kubectl apply -f -
          echo "Creating ConfigMap with notebooks..."
          kubectl create configmap jupyterlab-notebooks \
            --from-file=regression_dashboard.ipynb=tests/fixtures/notebooks/regression_dashboard.ipynb \
            --from-file=pagination_loop_test.ipynb=tests/fixtures/playbooks/pagination/loop_with_pagination/pagination_loop_test.ipynb \
            -n noetl \
            --dry-run=client -o yaml | kubectl apply -f -
          kubectl apply -f ci/manifests/jupyterlab/pvc.yaml
          kubectl apply -f ci/manifests/jupyterlab/deployment.yaml
          kubectl apply -f ci/manifests/jupyterlab/service.yaml
          echo "✓ JupyterLab deployed"
          echo "  Access at http://localhost:30888"
          echo "  Token noetl"
          echo "  Notebooks:"
          echo "    - /work/notebooks/regression_dashboard.ipynb"
          echo "    - /work/notebooks/pagination_loop_test.ipynb"
    next:
      spec:
        mode: exclusive
      arcs:
        - step: end

  - step: undeploy_jupyterlab
    desc: Remove JupyterLab from kind cluster
    tool:
      kind: shell
      cmds:
        - |
          echo ""
          echo "Removing JupyterLab..."
          kubectl delete -f ci/manifests/jupyterlab/service.yaml --ignore-not-found=true
          kubectl delete -f ci/manifests/jupyterlab/deployment.yaml --ignore-not-found=true
          kubectl delete -f ci/manifests/jupyterlab/pvc.yaml --ignore-not-found=true
          kubectl delete configmap jupyterlab-notebooks -n noetl --ignore-not-found=true
          echo "✓ JupyterLab removed"
    next:
      spec:
        mode: exclusive
      arcs:
        - step: end

  - step: full_deployment
    desc: Complete JupyterLab deployment workflow
    tool:
      kind: shell
      cmds:
        - |
          echo ""
          echo "Running complete JupyterLab deployment workflow..."
          echo "Deploying JupyterLab to noetl namespace..."
          kubectl create namespace noetl --dry-run=client -o yaml | kubectl apply -f -
          echo "Creating ConfigMap with notebooks..."
          kubectl create configmap jupyterlab-notebooks \
            --from-file=regression_dashboard.ipynb=tests/fixtures/notebooks/regression_dashboard.ipynb \
            --from-file=pagination_loop_test.ipynb=tests/fixtures/playbooks/pagination/loop_with_pagination/pagination_loop_test.ipynb \
            -n noetl \
            --dry-run=client -o yaml | kubectl apply -f -
          kubectl apply -f ci/manifests/jupyterlab/pvc.yaml
          kubectl apply -f ci/manifests/jupyterlab/deployment.yaml
          kubectl apply -f ci/manifests/jupyterlab/service.yaml
          echo "✓ JupyterLab deployed"
          echo "  Access at http://localhost:30888"
          echo "  Token noetl"
          echo "  Notebooks:"
          echo "    - /work/notebooks/regression_dashboard.ipynb"
          echo "    - /work/notebooks/pagination_loop_test.ipynb"
          
          echo "Testing JupyterLab deployment..."
          kubectl wait --for=condition=ready pod -l app=jupyterlab -n noetl --timeout=300s
          POD_NAME=$(kubectl get pod -n noetl -l app=jupyterlab -o jsonpath='{.items[0].metadata.name}')
          echo "Testing HTTP endpoint..."
          kubectl exec -n noetl $POD_NAME -- curl -s http://localhost:8888 | grep -q "JupyterLab" && echo "✓ JupyterLab is responding" || echo "✗ JupyterLab not responding"
          echo "Checking notebook file..."
          kubectl exec -n noetl $POD_NAME -- ls -lh /home/jovyan/work/notebooks/regression_dashboard.ipynb && echo "✓ Notebook found" || echo "✗ Notebook not found"
          echo "Checking Python packages..."
          kubectl exec -n noetl $POD_NAME -- python -c "import psycopg, duckdb, polars, pyarrow, plotly; print('✓ All packages installed')" || echo "✗ Package installation failed"
          echo "✓ JupyterLab deployment test completed"
          
          echo ""
          echo "========================================="
          echo "JupyterLab is ready!"
          echo "========================================="
          echo "  URL http://localhost:30888"
          echo "  Token noetl"
          echo "  Notebook /work/notebooks/regression_dashboard.ipynb"
          echo ""
          echo "Run regression test"
          echo "  1. Open notebook in browser"
          echo "  2. Run all cells (Cell -> Run All)"
          echo "  3. Monitor test execution and view results"
          echo "========================================="
    next:
      spec:
        mode: exclusive
      arcs:
        - step: end

  - step: check_status
    desc: Check JupyterLab deployment status
    tool:
      kind: shell
      cmds:
        - |
          echo ""
          echo "JupyterLab Deployment Status:"
          echo "============================="
          echo "JupyterLab Status"
          kubectl get deployment jupyterlab -n noetl -o wide || echo "  Deployment not found"
          kubectl get service jupyterlab -n noetl || echo "  Service not found"
          kubectl get pvc jupyterlab-pvc -n noetl || echo "  PVC not found"
          kubectl get configmap jupyterlab-notebooks -n noetl || echo "  ConfigMap not found"
          echo ""
          echo "Pods"
          kubectl get pods -n noetl -l app=jupyterlab -o wide || echo "  No pods found"
    next:
      spec:
        mode: exclusive
      arcs:
        - step: end

  - step: view_logs
    desc: View JupyterLab logs
    tool:
      kind: shell
      cmds:
        - |
          echo ""
          echo "JupyterLab Logs:"
          echo "================"
          kubectl logs -n noetl -l app=jupyterlab --tail=100 -f
    next:
      spec:
        mode: exclusive
      arcs:
        - step: end

  - step: port_forward
    desc: Port-forward JupyterLab service to localhost
    tool:
      kind: shell
      cmds:
        - |
          echo ""
          echo "Port-forwarding JupyterLab to localhost 8888..."
          echo "Access at http://localhost:30888 (token noetl)"
          kubectl port-forward -n noetl service/jupyterlab 8888:8888
    next:
      spec:
        mode: exclusive
      arcs:
        - step: end

  - step: restart_deployment
    desc: Restart JupyterLab deployment
    tool:
      kind: shell
      cmds:
        - |
          echo ""
          echo "Restarting JupyterLab..."
          kubectl rollout restart deployment/jupyterlab -n noetl
          kubectl rollout status deployment/jupyterlab -n noetl
          echo "✓ JupyterLab restarted"
    next:
      spec:
        mode: exclusive
      arcs:
        - step: end

  - step: open_shell
    desc: Open shell in JupyterLab pod
    tool:
      kind: shell
      cmds:
        - |
          echo ""
          echo "Opening shell in JupyterLab pod..."
          POD_NAME=$(kubectl get pod -n noetl -l app=jupyterlab -o jsonpath='{.items[0].metadata.name}')
          kubectl exec -it -n noetl $POD_NAME -- /bin/bash
    next:
      spec:
        mode: exclusive
      arcs:
        - step: end

  - step: test_deployment
    desc: Test JupyterLab deployment
    tool:
      kind: shell
      cmds:
        - |
          echo ""
          echo "Testing JupyterLab deployment..."
          kubectl wait --for=condition=ready pod -l app=jupyterlab -n noetl --timeout=300s
          POD_NAME=$(kubectl get pod -n noetl -l app=jupyterlab -o jsonpath='{.items[0].metadata.name}')
          echo "Testing HTTP endpoint..."
          kubectl exec -n noetl $POD_NAME -- curl -s http://localhost:8888 | grep -q "JupyterLab" && echo "✓ JupyterLab is responding" || echo "✗ JupyterLab not responding"
          echo "Checking notebook file..."
          kubectl exec -n noetl $POD_NAME -- ls -lh /home/jovyan/work/notebooks/regression_dashboard.ipynb && echo "✓ Notebook found" || echo "✗ Notebook not found"
          echo "Checking Python packages..."
          kubectl exec -n noetl $POD_NAME -- python -c "import psycopg, duckdb, polars, pyarrow, plotly; print('✓ All packages installed')" || echo "✗ Package installation failed"
          echo "✓ JupyterLab deployment test completed"
    next:
      spec:
        mode: exclusive
      arcs:
        - step: end

  - step: update_notebook
    desc: Update notebook in ConfigMap and restart
    tool:
      kind: shell
      cmds:
        - |
          echo ""
          echo "Updating notebook ConfigMap..."
          kubectl create configmap jupyterlab-notebooks \
            --from-file=regression_dashboard.ipynb=tests/fixtures/notebooks/regression_dashboard.ipynb \
            -n noetl \
            --dry-run=client -o yaml | kubectl apply -f -
          echo "Restarting JupyterLab to pick up changes..."
          kubectl rollout restart deployment/jupyterlab -n noetl
          kubectl rollout status deployment/jupyterlab -n noetl
          echo "✓ Notebook updated and JupyterLab restarted"
    next:
      spec:
        mode: exclusive
      arcs:
        - step: end

  - step: show_help
    desc: Display available actions
    tool:
      kind: shell
      cmds:
        - |
          echo "=================================================="
          echo " JupyterLab Automation"
          echo "=================================================="
          echo ""
          echo "Usage:"
          echo "  noetl run automation/infrastructure/jupyterlab.yaml --set action=<action>"
          echo ""
          echo "Deployment Actions:"
          echo "  deploy          - Deploy JupyterLab to kind cluster"
          echo "  undeploy        - Remove JupyterLab from kind cluster"
          echo "  full            - Complete deployment workflow"
          echo "  status          - Check deployment status"
          echo ""
          echo "Operations:"
          echo "  logs            - View JupyterLab logs"
          echo "  port-forward    - Port-forward to localhost:8888"
          echo "  restart         - Restart JupyterLab deployment"
          echo "  shell           - Open shell in JupyterLab pod"
          echo "  test            - Test deployment"
          echo "  update-notebook - Update notebook ConfigMap and restart"
          echo ""
          echo "Examples:"
          echo "  # Full deployment workflow"
          echo "  noetl run automation/infrastructure/jupyterlab.yaml --set action=full"
          echo ""
          echo "  # Deploy JupyterLab"
          echo "  noetl run automation/infrastructure/jupyterlab.yaml --set action=deploy"
          echo ""
          echo "  # Check status"
          echo "  noetl run automation/infrastructure/jupyterlab.yaml --set action=status"
          echo ""
          echo "  # View logs"
          echo "  noetl run automation/infrastructure/jupyterlab.yaml --set action=logs"
          echo ""
          echo "  # Port-forward to localhost"
          echo "  noetl run automation/infrastructure/jupyterlab.yaml --set action=port-forward"
          echo ""
    next:
      spec:
        mode: exclusive
      arcs:
        - step: end

  - step: end
    desc: End workflow
    tool:
      kind: noop
