apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: postgres-exporter
  namespace: postgres
spec:
  endpoints:
    - port: metrics
      interval: 30s
  selector:
    matchLabels:
      app: postgres-exporter
  namespaceSelector:
    matchNames:
      - postgres
