apiVersion: workflow.noetl.io/v1
kind: Workflow
metadata:
  name: example-workflow
spec:
  vars:
    message1: hello
    message2: world
  timeout: 60
  initialSettings:
    start: [task1, task3]
    state: ready
  transitions:
    ready: [ running ]
    running: [ idle, paused, completed, failed, terminated ]
    idle: [ running ]
    paused: [ running ]
  tasks:
    task1:
      steps:
        command1:
          description: tratata
          type: shell
          command: "echo "
          args:
            - "{{ vars.message1 }}"
            - "{{ vars.message2 }}"
          # outputs:
          #   stdout: "hello world"
          #   stderr: ""
          #   exitCode: 0
        httpreq1:
          description: tratata
          type: http
          method: post
          url: "https://example.com/req1/{{ tasks.task1.steps.command1.stdout }}"
          headers:
            "x-my-header": tasks.task1.steps.command1.stdout
          requestBody:
            application/json: |
              {
                "{{ vars.message1 }}": "{{ vars.message2 }}"
              }
          # outputs:
              # statusCode: 401
              # responseType: application/json
              # responseBody: {}
      switch:
        - next: [task3, task5]
          condition: |
            tasks.task1.steps.command1.exitCode == 0 
            && tasks.task1.steps.httpreq1.statusCode == 200
        - next: [task11, task12]
          condition: |
            tasks.task1.steps.command1.stdout == "hello world"
            || tasks.task1.steps.httpreq1.statusCode == 201
        - next: [task25, task27]
