apiVersion: workflow.noetl.io/v1
kind: Workflow
metadata:
  name: example-workflow
spec:
  schedule: "*/5 * * * *"
  vars:
    timeout: 60
  initialSettings:
    template: execute-steps
    state: ready
  transitions:
    ready: [running]
    running: [idle, paused, completed, failed, terminated]
    idle: [running]
    paused: [running]
  conditions:
    - "'{{workflow.variables.example_workflow.status}}' == 'ready'"
  templates:
    - name: hello-world-template-1
      inputs:
        - example_input
      outputs:
        - example_output
      type: shell
      command: "echo '{{inputs.example_input}}'"
      args: "{{example_workflow.actions.action1.execute.shell.output}}"
    - name: hello-world-template-2
      type: shell
      command: "echo 'Hello, World 2'"
      output: "{{outputs.example_output}}"
    - name: http-request-template-1
      type: httpRequest
      method: GET
      url: "https://api.github.com/octocat"
      query: "{{example_workflow.actions.action1.execute.httpRequest.output}}"
    - name: python-script-template-1
      type: script
      interpreter: python
      source: |
        import json
        result = "hello world"
        print(f"{result}")
    - name: postgres-database-query-1
      type: postgres
      sql: "select * from emp where id = '{{inputs.id}}'"
      output: "{{outputs.example_output.sql}}"
    - name: message-template
      inputs:
        - message_content
      type: message
      content: "{{inputs.message_content}}"
      destination: "my-messaging-topic"
    - name: execute-steps
      type: steps
      steps:
      - name: step-1
        template: hello-world-template-1
        runtime: docker
        conditions:
          start:
            - "'{{example_workflow.actions.action2.status}}' == 'ready'"
          exit:
            - "'{{example_workflow.actions.action2.status}}' == 'idle'"
        envs:
          PATH: "/noetl/bin"
        inputs:
          greeting: "Hello, World 1"
        outputs:
          name: example_output
          value: "{{example_workflow.actions.action1.execute.shell.output}}"
      - name: step-2
        template: message-template-1
      - name: step-3
        template: hello-world-template-2
      - name: step-4
        template: execute-tasks
    - name: execute-tasks
      type: tasks
      tasks:
      - name: task-1
        template: hello-world-template-2
      - name: task-2
        template: hello-world-template-1
