apiVersion: workflow.noetl.io/v1
kind: Workflow
metadata:
  name: example-workflow
spec:
  schedule: "*/5 * * * *"
  vars:
    timeout: 60
  initialState: ready
  transitions:
    ready: [running]
    running: [idle, paused, completed, failed, terminated]
    idle: [running]
    paused: [running]
  conditions:
    - "'{{workflow.variables.example_workflow.status}}' == 'ready'"
  jobs:
    - name: job1
      runtime: docker
      conditions:
        - "'{{example_workflow.jobs.job2.status}}' == 'ready'"
      envs:
        PATH: "/noetl/bin"
      args: "{{example_workflow.jobs.job1.tasks.task1.output}}"
      tasks:
        - name: task1
          execute:
            - type: shell
              command: "echo 'Hello, World 1'"
              args: "{{example_workflow.jobs.job1.tasks.task1.output}}"
            - type: shell
              command: "echo 'Hello, World 2'"
            - type: httpRequest
              method: GET
              url: "https://api.github.com/octocat"
              query: "{{example_workflow.jobs.job1.tasks.task1.output}}"

    - name: job2
      runtime: kubernetes
      schedule: "0 12 * * *"
      tasks:
        - name: task1
          conditions:
            - "'{{example_workflow.jobs.job1.tasks.task1.status}}' == 'completed'"
          execute:
            - type: shell
              command: "echo 'Job2 Task1'"
