apiVersion: workflow.noetl.io/v1
kind: Workflow
metadata:
  name: tradetrend-realtime-data-load-workflow
spec:
  vars:
    username: username
    database: dbname
  schedule: "10 */5 * * *"
  initialSettings:
    start: [task1]
    state: ready
  transitions:
    ready: [ running ]
    running: [ idle, paused, completed, failed, terminated ]
    idle: [ running ]
    paused: [ running ]
  tasks:
    task_1:
      steps:
        step_1:
          description: task 1 step 1
          type: shell
          command: psql -h localhost -p 5432 -U {{spec.vars.username}} -d {{spec.vars.database}} -c "CALL load_data_ibkr_realtime2data_raw2data();"
        step_2:
          description: task 1 step 2
          type: shell
          command: psql -h localhost -p 5432 -U {{spec.vars.username}} -d {{spec.vars.database}} -c "CALL initial_calculation();"
          condition: |
            {{ tasks.task_1.steps.step_1.exitCode }} == 0
            && now().strftime('%M') | int >= 5
            && now().strftime('%M') | int < 10
      switch:
        - next: [task_2]
          condition: |
            {{ tasks.task_1.steps.step_1.exitCode }} == 0
            && {{ tasks.task_1.steps.step_2.exitCode }} == 0
    task_2:
      steps:
        step_1:
          description: task 2 step 1
          type: shell
          command: psql -h localhost -p 5432 -U {{spec.vars.username}} -d {{spec.vars.database}} -c "CALL run_at_setup_group_trades(0, false);"
