apiVersion: workflow.noetl.io/v1
kind: Workflow
metadata:
  name: tradetrend-realtime-data-load-workflow
spec:
  vars:
    username: username
    database: dbname
  schedule: "*/5 * * * *"
  initialSettings:
    start: [task1]
    state: ready
  transitions:
    ready: [ running ]
    running: [ idle, paused, completed, failed, terminated ]
    idle: [ running ]
    paused: [ running ]
  tasks:
    task1:
      steps:
        command1:
          description: task 1
          type: shell
          command: psql -h localhost -p 5432 -U {{spec.vars.username}} -d {{spec.vars.database}} -c "CALL load_data_ibkr_realtime2data_raw2data();"
      switch:
        - next: [task2]
          condition: |
            {{ tasks.task1.steps.command1.exitCode }} == 0
            && now().strftime('%M') | int >= 5
            && now().strftime('%M') | int < 10
        - next: [task3]
          condition: |
            {{ tasks.task1.steps.command1.exitCode }} == 0
    task2:
      steps:
        command1:
          description: task 2
          type: shell
          command: psql -h localhost -p 5432 -U {{spec.vars.username}} -d {{spec.vars.database}} -c "CALL initial_calculation();"
      switch:
        - next: [task3]
          condition: |
            {{ tasks.task2.steps.command1.exitCode }} == 0
    task3:
      steps:
        command1:
          description: task 3
          type: shell
          command: psql" -h localhost -p 5434 -U {{spec.vars.username}} -d {{spec.vars.database}} -c "CALL run_at_setup_group_trades(0, false);"
