apiVersion: noetl.io/v2
kind: Playbook
metadata:
  name: noetl_development_deploy
  path: automation/development/noetl
  description: Build/load/deploy helpers for NoETL in local kind

executor:
  profile: local
  version: noetl-runtime/1
workload:
  action: help  # build, load, deploy, redeploy, status
  registry: "local"
  image_name: "noetl"

workflow:
  - step: route_action
    desc: Entry point - route based on action parameter
    tool:
      kind: shell
      cmds:
        - echo "NoETL Deploy Automation - Action '{{ workload.action }}'"
    next:
      spec:
        mode: exclusive
      arcs:
        - step: build_image
          when: "{{ workload.action == 'build' }}"
        - step: load_image
          when: "{{ workload.action == 'load' }}"
        - step: deploy_noetl
          when: "{{ workload.action == 'deploy' }}"
        - step: build_image
          when: "{{ workload.action == 'redeploy' }}"
        - step: status
          when: "{{ workload.action == 'status' }}"
        - step: show_help
          when: "{{ workload.action == 'help' }}"
        - step: show_help

  - step: build_image
    desc: Build NoETL Docker image
    tool:
      kind: shell
      cmds:
        - |
          echo ""
          echo "Building NoETL Docker image..."
          IMAGE_TAG=$(date +%Y-%m-%d-%H-%M)
          echo "$IMAGE_TAG" > .noetl_last_build_tag.txt
          echo "Building with tag: $IMAGE_TAG"
          docker buildx build --load --platform linux/amd64 \
            -t {{ workload.registry }}/{{ workload.image_name }}:$IMAGE_TAG \
            -f docker/noetl/dev/Dockerfile .
          echo ""
          echo "Build complete: {{ workload.registry }}/{{ workload.image_name }}:$IMAGE_TAG"
    next:
      spec:
        mode: exclusive
      arcs:
        - step: load_image
          when: "{{ workload.action == 'redeploy' }}"
        - step: end

  - step: load_image
    desc: Load Docker image into kind cluster
    tool:
      kind: shell
      cmds:
        - |
          echo ""
          echo "Loading image into kind cluster..."
          if [ ! -f .noetl_last_build_tag.txt ]; then
            echo "ERROR: .noetl_last_build_tag.txt not found. Run 'build' action first."
            exit 1
          fi
          IMAGE_TAG=$(cat .noetl_last_build_tag.txt)
          IMAGE="{{ workload.registry }}/{{ workload.image_name }}:$IMAGE_TAG"
          echo "Loading image: $IMAGE"
          kind load docker-image "$IMAGE" --name noetl
          echo ""
          echo "Image loaded successfully"
    next:
      spec:
        mode: exclusive
      arcs:
        - step: deploy_noetl
          when: "{{ workload.action == 'redeploy' }}"
        - step: end

  - step: deploy_noetl
    desc: Deploy NoETL server and workers
    tool:
      kind: shell
      cmds:
        - |
          echo ""
          echo "Deploying NoETL..."
          kubectl apply -f ci/manifests/noetl/namespace/

          if [ ! -f .noetl_last_build_tag.txt ]; then
            echo "ERROR: .noetl_last_build_tag.txt not found. Build must have failed."
            exit 1
          fi
          IMAGE_TAG=$(cat .noetl_last_build_tag.txt)
          IMAGE="{{ workload.registry }}/{{ workload.image_name }}:$IMAGE_TAG"
          echo "Using image: $IMAGE"

          for manifest in ci/manifests/noetl/*.yaml; do
            if [ -f "$manifest" ]; then
              sed "s|image_name:image_tag|$IMAGE|g" "$manifest" | kubectl apply -f -
            fi
          done

          echo ""
          echo "Restarting NoETL deployments to pick up new image..."
          kubectl rollout restart deployment/noetl-server -n noetl 2>/dev/null || true
          kubectl rollout restart deployment/noetl-worker -n noetl 2>/dev/null || true

          echo ""
          echo "Waiting for NoETL server..."
          kubectl wait --for=condition=ready pod -l app=noetl-server -n noetl --timeout=90s || echo "Warning: NoETL server not ready"
          echo "Waiting for NoETL workers..."
          kubectl wait --for=condition=ready pod -l app=noetl-worker -n noetl --timeout=90s || echo "Warning: NoETL workers not ready"
    next:
      spec:
        mode: exclusive
      arcs:
        - step: status

  - step: status
    desc: Show NoETL pod and service status
    tool:
      kind: shell
      cmds:
        - |
          echo ""
          echo "NoETL status:"
          kubectl get pods -n noetl
          echo ""
          kubectl get svc -n noetl
    next:
      spec:
        mode: exclusive
      arcs:
        - step: end

  - step: show_help
    desc: Display available actions
    tool:
      kind: shell
      cmds:
        - |
          echo "=================================================="
          echo " NoETL Deploy Automation"
          echo "=================================================="
          echo ""
          echo "Usage:"
          echo "  noetl run automation/development/noetl.yaml --set action=<action>"
          echo ""
          echo "Actions:"
          echo "  build    - Build NoETL Docker image"
          echo "  load     - Load image into kind cluster"
          echo "  deploy   - Deploy NoETL server and workers"
          echo "  redeploy - Full cycle: build, load, deploy"
          echo "  status   - Show NoETL pod and service status"
          echo "  help     - Show this help"
          echo ""
          echo "Examples:"
          echo "  # Full rebuild and deploy"
          echo "  noetl run automation/development/noetl.yaml --set action=redeploy"
          echo ""
          echo "  # Just deploy (after manual build)"
          echo "  noetl run automation/development/noetl.yaml --set action=deploy"
    next:
      spec:
        mode: exclusive
      arcs:
        - step: end

  - step: end
    desc: Done
    tool:
      kind: noop
