addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.3.2")
addSbtPlugin("com.typesafe.sbt" % "sbt-twirl"           % "1.3.13")
addSbtPlugin("com.eed3si9n"     % "sbt-buildinfo"       % "0.7.0")
addSbtPlugin("com.lucidchart"   % "sbt-scalafmt"        % "1.15")
addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.14.6")
