# NoETL DSL Playbook for Google Cloud Storage authentication using secrets.
# This playbook showcases how to:
# - Retrieve GCS HMAC credentials from Google Secret Manager
# - Create a DuckDB secret for GCS authentication using the CREATE SECRET syntax
# - Use this secret for GCS operations
# Usage:
# noetl playbook --register playbook/gcs_secrets_example.yaml --port 8080
# noetl playbook --execute --path "workflows/examples/gcs_secrets_example" --payload '{"GOOGLE_CLOUD_PROJECT": "noetl-demo-19700101"}'

apiVersion: noetl.io/v1
kind: Playbook
name: gcs_secrets_example
path: examples/gcs_secrets_example

workload:
  jobId: "{{ job.uuid }}"
  gs_project_id: "{{ env.GOOGLE_CLOUD_PROJECT | default('noetl-demo-19700101') }}"
  gs_bucket: "noetl-demo-19700101"
  gcs_key_id_secret: "{{ env.GCS_KEY_ID_SECRET | default('gcs-key-id') }}"
  gcs_secret_key_secret: "{{ env.GCS_SECRET_KEY_SECRET | default('gcs-secret-key') }}"
  source_csv_path: "data/test/test_data.csv"
  gs_csv_path: "uploads/test_data.csv"

workflow:
  - step: start
    desc: "Start GCS Secrets Example Workflow"
    next:
      - step: get_gcs_key_id

  - step: get_gcs_key_id
    desc: "Retrieve GCS HMAC Key ID from Google Secret Manager"
    type: workbook
    task: get_gcs_key_id_task
    next:
      - step: get_gcs_secret_key

  - step: get_gcs_secret_key
    desc: "Retrieve GCS HMAC Secret Key from Google Secret Manager"
    type: workbook
    task: get_gcs_secret_key_task
    next:
      - step: create_gcs_secret

  - step: create_gcs_secret
    desc: "Create DuckDB secret for GCS authentication"
    type: workbook
    task: create_gcs_secret_task
    input:
      key_id: "{{ get_gcs_key_id.secret_value }}"
      secret_key: "{{ get_gcs_secret_key.secret_value }}"
    next:
      - step: upload_csv_to_gs

  - step: upload_csv_to_gs
    desc: "Upload CSV file to Google Storage bucket using the created secret"
    type: workbook
    task: upload_csv_task
    input:
      key_id: "{{ get_gcs_key_id.secret_value }}"
      secret_key: "{{ get_gcs_secret_key.secret_value }}"
    next:
      - step: end

  - step: end
    desc: "End of workflow"

workbook:
  - name: get_gcs_key_id_task
    type: secrets
    provider: google
    project_id: "noetl-demo-19700101"
    secret_name: "gcs-key-id"

  - name: get_gcs_secret_key_task
    type: secrets
    provider: google
    project_id: "noetl-demo-19700101"
    secret_name: "gcs-secret-key"

  - name: create_gcs_secret_task
    type: duckdb
    input:
      key_id: "{{ key_id }}"
      secret_key: "{{ secret_key }}"
    command: |
      INSTALL httpfs;
      LOAD httpfs;
      SET s3_endpoint='storage.googleapis.com';
      SET s3_region='auto';
      SET s3_url_style='path';
      SET s3_use_ssl=true;
      CREATE OR REPLACE SECRET gcs_secret (
          TYPE S3,
          KEY_ID '{{ key_id }}',
          SECRET '{{ secret_key }}'
      );
      CREATE TABLE test_gcs_secret AS
      SELECT 'GCS secret created successfully' as status, CURRENT_TIMESTAMP as timestamp;

  - name: upload_csv_task
    type: duckdb
    input:
      key_id: "{{ key_id }}"
      secret_key: "{{ secret_key }}"
    command: |
      INSTALL httpfs;
      LOAD httpfs;
      SET s3_endpoint='storage.googleapis.com';
      SET s3_region='auto';
      SET s3_url_style='path';
      SET s3_use_ssl=true;
      CREATE OR REPLACE SECRET gcs_secret (
          TYPE S3,
          KEY_ID '{{ key_id }}',
          SECRET '{{ secret_key }}'
      );
      CREATE TABLE temp_csv AS 
      SELECT * FROM read_csv_auto('{{ workload.source_csv_path }}', 
                                 all_varchar=false,  
                                 sample_size=-1);    
      SELECT * FROM temp_csv LIMIT 5;
      DESCRIBE temp_csv;
      COPY temp_csv TO 'gs://{{ workload.gs_bucket }}/{{ workload.gs_csv_path }}' (FORMAT CSV, HEADER);
      SELECT COUNT(*) as uploaded_rows FROM read_csv_auto('gs://{{ workload.gs_bucket }}/{{ workload.gs_csv_path }}');
      DROP TABLE temp_csv;
