apiVersion: noetl.io/v1
kind: Playbook
name: secrets_test
path: examples/secrets_test
workload:
  jobId: '{{ job.uuid }}'
  execution_id: '{{ job.uuid }}'
  gs_project_id: noetl-demo-19700101
  secret_name: test-secret
  environment: dev
workflow:
- step: start
  desc: Start Secrets Test Workflow
  next:
  - step: get_secret_step
- step: get_secret_step
  desc: Retrieve a test secret
  type: workbook
  task: get_secret_task
  next:
  - step: use_secret_step
- data:
    secret: '{{ get_secret_step.secret_value }}'
  step: use_secret_step
  desc: Use the retrieved secret
  type: workbook
  task: use_secret_task
  next:
  - step: end
- step: end
  desc: End of workflow
workbook:
- name: get_secret_task
  type: secrets
  provider: google
  project_id: noetl-demo-19700101
  secret_name: test-secret
- data:
    secret: '{{ secret }}'
  name: use_secret_task
  type: python
  code: "def main(secret):\n    print(f\"Retrieved secret: {secret}\")\n\n    return\
    \ {\n        \"status\": \"success\",\n        \"message\": \"Successfully retrieved\
    \ and used the secret\",\n        \"secret_length\": len(secret),\n        \"\
    environment\": \"dev\"\n    }\n"
