version: 0.1
name: demo_workflow
working_directory: .
  shell: /bin/bash
  environment:
    ENV: staging
jobs:
   demo_create_files:
      name: Demonstration of terminal execution
      vars:
         HOST: ${HOST}
         ENVIRONMENT: ${ENV}
         DIR: ${WORKING_DIR}
      inputs:
         rules_arguments:
            name: start arguments
            type: string
            value: vars.ENVIRONMENT
      outputs:
         message_exit_code:
            name: job exit code
            value: another_task.message_exit_code
      tasks:
         start:
            name: Hello
            type: shell,ssh,rest
            vars:
               msg: Hello ${HOST}
            deps:
               rule1: x==4
               rule2: y==5
            loop:
               from: 1
               to: 10
               increment: 1
               exclude: [5,6]
               file: filename
               wait: 1s
               parallel: true, false
            exec (call):
              - echo ${.msg}
              - echo "Bye ${loop.value}"
            outputs:
               message_exit_code: exit_code
               failures: number_of_failures
         another_task:
            name: Task #2
            type: shell,ssh,rest
            vars:
               msg: Hello ${HOST}
            deps:
               rule1: x==4
               rule2: y==5
            loop:
               from: 1
               to: 10
               increment: 1
               exclude: [5,6]
               file: filename
               wait: 1s
               parallel: true, false
            exec (call):
              - echo ${.msg}
              - echo "Bye ${loop.value}"
            outputs:
               message_exit_code: exit_code
               failures: number_of_failures
