---
apiVersion: noetl.io/v1
kind: Playbook
metadata:
  name: duckdb_snowflake_query
  path: examples/duckdb_snowflake_query
  description: |
    Query Snowflake data using DuckDB's Snowflake extension.
    
    This playbook demonstrates:
    - Loading Snowflake extension in DuckDB
    - Using Snowflake credentials from NoETL credential table
    - Querying Snowflake tables via DuckDB
    - Exporting results to local files

workload:
  snowflake_credential: snowflake_test
  output_path: /tmp/snowflake_query_results.parquet

workflow:
  - step: start
    desc: Query Snowflake data via DuckDB
    type: duckdb
    auth:
      snowflake_db:
        type: snowflake
        credential: "{{ workload.snowflake_credential }}"
    with:
      commands: |
        -- Install and load Snowflake extension
        INSTALL snowflake FROM community;
        LOAD snowflake;
        
        -- Query Snowflake table and export to local file
        COPY (
          SELECT *
          FROM snowflake_db.ANALYTICS_DB.PUBLIC.SALES
          WHERE sale_date >= CURRENT_DATE - INTERVAL '30 days'
        ) TO '{{ workload.output_path }}' (FORMAT PARQUET);
        
        -- Show summary statistics
        SELECT 
          COUNT(*) as total_records,
          SUM(amount) as total_sales,
          AVG(amount) as avg_sale
        FROM snowflake_db.ANALYTICS_DB.PUBLIC.SALES
        WHERE sale_date >= CURRENT_DATE - INTERVAL '30 days';
    next:
      - step: end

  - step: end
    desc: Query completed
