apiVersion: noetl.io/v1
kind: Playbook
metadata:
  name: snowflake_simple_test
  path: examples/snowflake_simple
  description: Simple Snowflake connection test

workload:
  test_message: "Hello from NoETL!"

workflow:
  - step: start
    desc: Test Snowflake connection
    type: snowflake
    auth:
      sf:
        type: snowflake
        key: sf_test
    command: |
      -- Test basic connection
      SELECT CURRENT_VERSION() as snowflake_version;
      
      -- Show current session info
      SELECT 
        CURRENT_ACCOUNT() as account,
        CURRENT_USER() as user,
        CURRENT_ROLE() as role,
        CURRENT_WAREHOUSE() as warehouse,
        CURRENT_DATABASE() as database,
        CURRENT_SCHEMA() as schema,
        CURRENT_REGION() as region;
      
      -- Simple calculation
      SELECT 
        '{{ workload.test_message }}' as message,
        CURRENT_TIMESTAMP() as timestamp,
        1 + 1 as simple_math;
    next:
      - step: end
  
  - step: end
    desc: Done
    type: python
    code: |
      def main(input_data):
          return {
              'status': 'success',
              'message': 'Snowflake connection test completed'
          }
