# Snowflake Credential Configuration for NoETL
#
# This file contains credential configurations for Snowflake connections.
# Register this file with NoETL using:
#   noetl auth register snowflake_credentials.yaml --host localhost --port 8083

apiVersion: noetl.io/v1
kind: Credential

credentials:
  - key: sf_test
    name: Snowflake Test Account
    description: Snowflake test account credentials
    type: snowflake
    data:
      account: "YOUR_ACCOUNT_IDENTIFIER"  # e.g., xy12345.us-east-1 or xy12345.us-east-1.aws
      user: "YOUR_USERNAME"
      password: "YOUR_PASSWORD"
      warehouse: "COMPUTE_WH"  # Default warehouse
      database: ""  # Optional: default database
      schema: "PUBLIC"  # Optional: default schema
      role: ""  # Optional: default role
      authenticator: "snowflake"  # snowflake, externalbrowser, or oauth
    
  - key: sf_prod
    name: Snowflake Production Account
    description: Snowflake production account credentials (example)
    type: snowflake
    data:
      account: "YOUR_PROD_ACCOUNT"
      user: "YOUR_PROD_USER"
      password: "YOUR_PROD_PASSWORD"
      warehouse: "PROD_WH"
      database: "PROD_DB"
      schema: "PUBLIC"
      role: "PROD_ROLE"
      authenticator: "snowflake"

---
# Alternative: Use environment variables for security
# Register credentials that reference environment variables

apiVersion: noetl.io/v1
kind: Credential

credentials:
  - key: sf_env
    name: Snowflake from Environment
    description: Snowflake credentials from environment variables
    type: snowflake
    data:
      account: "${SNOWFLAKE_ACCOUNT}"
      user: "${SNOWFLAKE_USER}"
      password: "${SNOWFLAKE_PASSWORD}"
      warehouse: "${SNOWFLAKE_WAREHOUSE:-COMPUTE_WH}"
      database: "${SNOWFLAKE_DATABASE:-}"
      schema: "${SNOWFLAKE_SCHEMA:-PUBLIC}"
      role: "${SNOWFLAKE_ROLE:-}"
