apiVersion: apps/v1
kind: Deployment
metadata:
  name: noetl-package
  labels:
    app: noetl-package
spec:
  replicas: 1
  selector:
    matchLabels:
      app: noetl-package
  template:
    metadata:
      labels:
        app: noetl-package
    spec:
      containers:
      - name: noetl-package
        image: python:3.12-slim
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: noetl-config
        - secretRef:
            name: noetl-secret
        volumeMounts:
        - name: noetl-data
          mountPath: /opt/noetl/data
        - name: noetl-package
          mountPath: /opt/noetl/package
        command:
        - sh
        - -c
        resources:
          limits:
            cpu: '1'
            memory: 1Gi
          requests:
            cpu: '0.5'
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      volumes:
      - name: noetl-data
        emptyDir: {}
      - name: noetl-package
        hostPath:
          path: /path/to/local/noetl/package
          type: Directory
