apiVersion: apps/v1
kind: Deployment
metadata:
  name: noetl-dev
  labels:
    app: noetl-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: noetl-dev
  template:
    metadata:
      labels:
        app: noetl-dev
    spec:
      containers:
        - name: noetl-dev
          image: noetl-local-dev:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: noetl-config
            - secretRef:
                name: noetl-secret
          env:
            - name: NOETL_PORT
              value: "8080"
            - name: NOETL_INTERNAL_URL
              value: "http://127.0.0.1:8080"
            - name: NOETL_BASE_URL
              value: "http://127.0.0.1:8080"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/opt/noetl/.secrets/noetl-service-account.json"
          volumeMounts:
            - name: noetl-data
              mountPath: /opt/noetl/data
            - name: gcp-sa
              mountPath: /opt/noetl/.secrets
              readOnly: true
          resources:
            limits:
              cpu: "2"
              memory: "3Gi"
            requests:
              cpu: "0.5"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 5
      volumes:
        - name: noetl-data
          emptyDir: {}
        - name: noetl-local-repo
          emptyDir: {}
        - name: gcp-sa
          secret:
            secretName: noetl-gcp-service-account
            items:
              - key: noetl-service-account.json
                path: noetl-service-account.json
