apiVersion: apps/v1
kind: Deployment
metadata:
  name: noetl-worker-cpu-01
  labels:
    app: noetl-worker
    component: worker
    runtime: cpu
    worker-pool: worker-cpu-01
  namespace: noetl-worker-cpu-01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: noetl-worker
      worker-pool: worker-cpu-01
  template:
    metadata:
      labels:
        app: noetl-worker
        component: worker
        runtime: cpu
        worker-pool: worker-cpu-01
    spec:
      initContainers:
        - name: wait-for-api
          image: curlimages/curl:8.7.1
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - >-
              until curl -sf http://noetl.noetl.svc.cluster.local:8082/api/health; do
                echo "Waiting for NoETL API...";
                sleep 3;
              done
      containers:
        - name: worker
          image: noetl-local-dev:latest
          imagePullPolicy: IfNotPresent
          command: ["noetl"]
          args: ["worker", "start"]
          envFrom:
            - configMapRef:
                name: noetl-config
            - secretRef:
                name: noetl-secret
          env:
            - name: NOETL_RUN_MODE
              value: "worker"
            - name: NOETL_SERVER_URL
              value: "http://noetl.noetl.svc.cluster.local:8082"
            - name: NOETL_WORKER_POOL_RUNTIME
              value: "cpu"
            - name: NOETL_WORKER_POOL_NAME
              value: "worker-cpu-01-k8s"
          volumeMounts:
            - name: noetl-data
              mountPath: /opt/noetl/data
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      volumes:
        - name: noetl-data
          emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: noetl-worker-cpu-02
  labels:
    app: noetl-worker
    component: worker
    runtime: cpu
    worker-pool: worker-cpu-02
  namespace: noetl-worker-cpu-02
spec:
  replicas: 1
  selector:
    matchLabels:
      app: noetl-worker
      worker-pool: worker-cpu-02
  template:
    metadata:
      labels:
        app: noetl-worker
        component: worker
        runtime: cpu
        worker-pool: worker-cpu-02
    spec:
      initContainers:
        - name: wait-for-api
          image: curlimages/curl:8.7.1
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - >-
              until curl -sf http://noetl.noetl.svc.cluster.local:8082/api/health; do
                echo "Waiting for NoETL API...";
                sleep 3;
              done
      containers:
        - name: worker
          image: noetl-local-dev:latest
          imagePullPolicy: IfNotPresent
          command: ["noetl"]
          args: ["worker", "start"]
          envFrom:
            - configMapRef:
                name: noetl-config
            - secretRef:
                name: noetl-secret
          env:
            - name: NOETL_RUN_MODE
              value: "worker"
            - name: NOETL_SERVER_URL
              value: "http://noetl.noetl.svc.cluster.local:8082"
            - name: NOETL_WORKER_POOL_RUNTIME
              value: "cpu"
            - name: NOETL_WORKER_POOL_NAME
              value: "worker-cpu-02-k8s"
          volumeMounts:
            - name: noetl-data
              mountPath: /opt/noetl/data
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      volumes:
        - name: noetl-data
          emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: noetl-worker-gpu-01
  labels:
    app: noetl-worker
    component: worker
    runtime: gpu
    worker-pool: worker-gpu-01
  namespace: noetl-worker-gpu-01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: noetl-worker
      worker-pool: worker-gpu-01
  template:
    metadata:
      labels:
        app: noetl-worker
        component: worker
        runtime: gpu
        worker-pool: worker-gpu-01
    spec:
      initContainers:
        - name: wait-for-api
          image: curlimages/curl:8.7.1
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - >-
              until curl -sf http://noetl.noetl.svc.cluster.local:8082/api/health; do
                echo "Waiting for NoETL API...";
                sleep 3;
              done
      containers:
        - name: worker
          image: noetl-local-dev:latest
          imagePullPolicy: IfNotPresent
          command: ["noetl"]
          args: ["worker", "start"]
          envFrom:
            - configMapRef:
                name: noetl-config
            - secretRef:
                name: noetl-secret
          env:
            - name: NOETL_RUN_MODE
              value: "worker"
            - name: NOETL_SERVER_URL
              value: "http://noetl.noetl.svc.cluster.local:8082"
            - name: NOETL_WORKER_POOL_RUNTIME
              value: "gpu"
            - name: NOETL_WORKER_POOL_NAME
              value: "worker-gpu-01-k8s"
          volumeMounts:
            - name: noetl-data
              mountPath: /opt/noetl/data
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
      volumes:
        - name: noetl-data
          emptyDir: {}
