apiVersion: apps/v1
kind: Deployment
metadata:
  name: noetl
  labels:
    app: noetl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: noetl
  template:
    metadata:
      labels:
        app: noetl
    spec:
      containers:
        - name: noetl
          image: noetl-pip:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8084
          envFrom:
            - configMapRef:
                name: noetl-config
            - secretRef:
                name: noetl-secret
          env:
            - name: NOETL_INTERNAL_URL
              value: "http://noetl:8084"
            - name: NOETL_BASE_URL
              value: "http://noetl:8084"
          volumeMounts:
            - name: noetl-data
              mountPath: /opt/noetl/data
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "0.5"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8084
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8084
            initialDelaySeconds: 60
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
      volumes:
        - name: noetl-data
          emptyDir: {}
