apiVersion: batch/v1
kind: Job
metadata:
  name: noetl-apply-schema
  namespace: postgres
  labels:
    app: noetl-apply-schema
spec:
  ttlSecondsAfterFinished: 600
  backoffLimit: 2
  template:
    metadata:
      labels:
        app: noetl-apply-schema
    spec:
      restartPolicy: Never
      containers:
      - name: apply-schema
        image: ${NOETL_IMAGE:-ghcr.io/noetl/noetl}:${NOETL_TAG:-latest}
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - -c
        env:
        - name: POSTGRES_HOST
          value: postgres.postgres.svc.cluster.local
        - name: POSTGRES_PORT
          value: '5432'
        envFrom:
        - configMapRef:
            name: postgres-config
        - secretRef:
            name: postgres-secret
