apiVersion: noetl.io/v2
kind: Playbook
metadata:
  name: http_example
  path: automation/examples/http

executor:
  profile: local
  version: noetl-runtime/1
workload:
  api_base: "https://jsonplaceholder.typicode.com"

workflow:
  - step: start
    desc: "Fetch data from REST API"
    tool:
      kind: noop
    next:
      spec:
        mode: exclusive
      arcs:
        - step: fetch_user

  - step: fetch_user
    desc: "Get user data"
    tool:
      kind: http
      method: GET
      url: "{{ workload.api_base }}/users/1"
    vars:
      user_data: "{{ fetch_user.result }}"
    next:
      spec:
        mode: exclusive
      arcs:
        - step: fetch_posts

  - step: fetch_posts
    desc: "Get user posts"
    tool:
      kind: http
      method: GET
      url: "{{ workload.api_base }}/posts"
      params:
        userId: "1"
    vars:
      posts_data: "{{ fetch_posts.result }}"
    next:
      spec:
        mode: exclusive
      arcs:
        - step: display_results

  - step: display_results
    desc: "Display fetched data"
    tool:
      kind: shell
      cmds:
        - "echo 'User data fetched successfully'"
        - "echo '{{ vars.user_data }}' | head -c 200"
        - "echo ''"
        - "echo 'Posts data fetched successfully'"
        - "echo '{{ vars.posts_data }}' | head -c 200"
    next:
      spec:
        mode: exclusive
      arcs:
        - step: end

  - step: end
    desc: End workflow
    tool:
      kind: noop
