apiVersion: noetl.io/v1
kind: Playbook
metadata:
  name: http_to_postgres_bulk
  path: examples/http_to_postgres_bulk

workload:
  api_url: "https://jsonplaceholder.typicode.com/posts"
  pg_auth: pg_local

workflow:
  - step: start
    desc: Start workflow
    next:
      - step: create_table

  - step: create_table
    desc: Create table for storing HTTP data
    tool: postgres
    auth: "{{ workload.pg_auth }}"
    command: |
      DROP TABLE IF EXISTS public.http_to_postgres_bulk;

      CREATE TABLE public.http_to_postgres_bulk (
        id SERIAL PRIMARY KEY,
        post_id INTEGER,
        user_id INTEGER,
        title TEXT,
        body TEXT,
        fetched_at TIMESTAMPTZ DEFAULT NOW()
      );
    next:
      - step: transfer_http_to_pg

  - step: transfer_http_to_pg
    desc: Transfer HTTP API data to PostgreSQL using bulk transfer
    tool: transfer
    source:
      type: http
      url: "{{ workload.api_url }}"
      method: GET
    target:
      type: postgres
      auth:
        source: credential
        tool: postgres
        key: "{{ workload.pg_auth }}"
      table: public.http_to_postgres_bulk
      mapping:
        post_id: id
        user_id: userId
        title: title
        body: body
    chunk_size: 10
    next:
      - step: show_count

  - step: show_count
    desc: Verify record count
    tool: postgres
    auth: "{{ workload.pg_auth }}"
    command: |
      SELECT COUNT(*) as records FROM public.http_to_postgres_bulk;
    next:
      - step: end

  - step: end
    desc: End workflow
