FROM python:3.11-slim
ARG PRJ_PATH
WORKDIR /usr/noetl

RUN apt-get update && apt-get install -y \
    gcc \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

COPY ${PRJ_PATH}/docker/plugins/requirements.txt .

COPY  ${PRJ_PATH}/noetl/__init__.py \
      ${PRJ_PATH}/noetl/plugin.py \
      ${PRJ_PATH}/noetl/keyval.py \
      ${PRJ_PATH}/noetl/payload.py \
      ${PRJ_PATH}/noetl/const.py \
      ${PRJ_PATH}/noetl/natstream.py ./noetl/

ENV PYTHONPATH=/usr/noetl

RUN pip install --no-cache-dir -r requirements.txt
