apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: noetl-scrape
  namespace: noetl
spec:
  endpoints:
    - path: /metrics
      interval: 30s
  selector:
    matchLabels:
      app: noetl-server
  namespaceSelector:
    matchNames:
      - noetl
  relabelConfigs:
    - sourceLabels: [__meta_kubernetes_service_name]
      targetLabel: service
    - sourceLabels: [__meta_kubernetes_namespace]
      targetLabel: namespace
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: pod
