"""Database utilities and SQL templates."""

from .sqlcmd import *  # noqa: F401,F403

__all__ = [
    # SQL Templates - Event Log
    'EVENT_LOG_INSERT_POSTGRES',
    'EVENT_LOG_INSERT_DUCKDB',
    'TRANSITION_INSERT_POSTGRES', 
    'TRANSITION_INSERT_DUCKDB',
    # SQL Templates - Loop Operations
    'LOOP_SELECT_POSTGRES',
    'LOOP_SELECT_DUCKDB',
    'LOOP_DETAILS_SELECT_POSTGRES',
    'LOOP_DETAILS_SELECT_DUCKDB',
    'ACTIVE_LOOPS_SELECT_POSTGRES',
    'ACTIVE_LOOPS_SELECT_DUCKDB',
    'GET_ACTIVE_LOOPS_POSTGRES',
    'GET_ACTIVE_LOOPS_DUCKDB',
    # SQL Templates - Workload
    'WORKLOAD_TABLE_EXISTS_POSTGRES',
    'WORKLOAD_TABLE_EXISTS_DUCKDB',
    'WORKLOAD_INSERT_POSTGRES',
    'WORKLOAD_INSERT_DUCKDB',
    'WORKLOAD_SELECT_POSTGRES',
    'WORKLOAD_SELECT_DUCKDB',
    # Add other SQL template exports as needed
]
