apiVersion: noetl.io/v2
kind: Playbook
metadata:
  name: noetl_destroy_wrapper
  path: automation/destroy
  description: Destroy the local kind environment

workflow:
  - step: start
    desc: Run destroy workflow
    tool:
      kind: playbook
      path: setup/destroy.yaml
    next:
      - step: end

  - step: end
    desc: Done
