apiVersion: noetl.io/v2
kind: Playbook
metadata:
  name: noetl_automation_main
  path: automation/main
  description: Main automation entry point for NoETL development workflows
workload:
  # Environment configuration
  registry: "local"
  image_name: "noetl"
  target: "{{ execution.target | default('help') }}"
workflow:
  - step: start
    desc: Entry point for automation workflows
    next:
      - when: "{{ workload.target == 'help' }}"
        then:
          - step: show_help
      - when: "{{ workload.target == 'bootstrap' }}"
        then:
          - step: bootstrap
      - when: "{{ workload.target == 'destroy' }}"
        then:
          - step: destroy
      - when: "{{ workload.target == 'dev' }}"
        then:
          - step: quick_dev
      - step: unknown_target
  
  - step: show_help
    desc: Display available automation targets
    tool:
      kind: python
      code: |
        result = {
          "status": "success",
          "data": {
            "message": """NoETL Automation Playbooks

Available targets:
  bootstrap   - Complete K8s environment setup (install tools + deploy all)
  destroy     - Destroy environment and clean up all resources
  dev         - Quick development cycle (build + redeploy)
  test        - Run complete test suite
  
Usage:
  noetl run automation/main bootstrap
  noetl run automation/main destroy
  noetl run automation/main dev

Individual workflows:
  automation/setup/bootstrap.yaml    - Complete environment setup
  automation/setup/destroy.yaml      - Teardown and cleanup
  automation/ci/build.yaml           - Build workflows
  automation/ci/deploy.yaml          - Deployment workflows
  automation/test/regression.yaml    - Test execution
"""
          }
        }
    next:
      - step: end
  
  - step: bootstrap
    desc: Run complete bootstrap workflow
    tool:
      kind: playbook
      path: automation/setup/bootstrap
    next:
      - step: end
  
  - step: destroy
    desc: Run destroy workflow
    tool:
      kind: playbook
      path: automation/setup/destroy
    next:
      - step: end
  
  - step: quick_dev
    desc: Quick development cycle
    tool:
      kind: playbook
      path: automation/ci/quick_dev
    next:
      - step: end
  
  - step: unknown_target
    desc: Handle unknown target
    tool:
      kind: python
      args:
        target: "{{ workload.target }}"
      code: |
        result = {
          "status": "error",
          "data": {
            "message": f"Unknown target: {target}",
            "available": ["bootstrap", "destroy", "dev", "test", "help"]
          }
        }
    next:
      - step: end
  
  - step: end
    desc: Workflow complete
