apiVersion: noetl.io/v2
kind: Playbook
metadata:
  name: test_automation
  path: automation/test

executor:
  profile: local
  version: noetl-runtime/1
workload:
  cluster: noetl
  pg_host: localhost
  pg_port: 54321

workflow:
  - step: start
    desc: "Entry point for test automation"
    tool:
      kind: noop
    next:
      - step: setup_all

  - step: register_credentials
    desc: "Register test credentials using noetl CLI"
    tool:
      kind: shell
      cmds:
        - "echo 'Registering credentials...'"
        - "./bin/noetl register credential tests/fixtures/credentials/pg_local.json"
        - "./bin/noetl register credential tests/fixtures/credentials/pg_demo.json"
        - "echo '✅ Credentials registered'"
    next:
      - step: end

  - step: register_playbooks
    desc: "Register all test playbooks"
    tool:
      kind: shell
      cmds:
        - "echo 'Registering playbooks...'"
        - "./bin/noetl register playbook tests/fixtures/playbooks/ --recursive"
        - "echo '✅ Playbooks registered'"
    next:
      - step: end

  - step: setup_all
    desc: "Complete test environment setup"
    tool:
      kind: noop
    next:
      - step: register_credentials
      - step: register_playbooks

  - step: end
    desc: "End workflow"
    tool:
      kind: noop
