= NoETL Workflow Configuration

The NoETL workflow configuration provides a powerful and flexible structure for managing complex processes. By specifying your workflows in structured config files, you can define various types of operations, conditions, and execution orders. This document outlines the structure and usage of the NoETL workflow configuration files.

== Configuration File Structure
A typical NoETL workflow configuration file has a YAML-based structure that contains several key sections: `apiVersion`, `kind`, `metadata`, `spec`, and under the `spec`, several other key elements such as `schedule`, `vars`, `initialTemplate`, `initialState`, `transitions`, `conditions`, and `templates`.

Below is a general structure of a NoETL workflow config file:
```
apiVersion: workflow.noetl.io/v1
kind: Workflow
metadata:
  name: example-workflow
spec:
  schedule: "*/5 * * * *"
  vars:
    timeout: 60
  initialTemplate: execute-steps
  initialState: ready
  transitions:
    ready: [running]
    running: [idle, paused, completed, failed, terminated]
    idle: [running]
    paused: [running]
  conditions:
    - "'{{workflow.variables.example_workflow.status}}' == 'ready'"
  templates:
    # list of templates
```

== Key Elements

=== apiVersion
This defines the version of the workflow API that the configuration file is intended to use.

=== kind
This describes the type of object that the configuration file represents. In this case, it would be `Workflow`.

=== metadata
This section includes data that helps uniquely identify the workflow. Currently, it includes the `name` of the workflow.

=== spec
The `spec` (short for specification) is where the majority of the workflow configuration is defined. It contains:

- `schedule`: A cron expression for the scheduling of the workflow.
- `vars`: Variables that can be used across the workflow.
- `initialTemplate`: The template to be executed first when the workflow starts.
- `initialState`: The initial state of the workflow.
- `transitions`: The valid state transitions of the workflow.
- `conditions`: Conditions that must be met for the workflow to execute.
- `templates`: Templates that define operations such as shell commands, HTTP requests, scripts, PostgreSQL queries, or other workflows.

=== templates
Templates are reusable, parameterized entities that encapsulate a certain type of operation or workflow. The `type` field determines the type of operation encapsulated by the template. The types can be:

- `shell`: Executes a command line statement. The command field specifies the statement to be executed.
- `httpRequest`: Executes a REST API call. The method, url, and query fields define the HTTP request.
- `script`: Runs a script, specified in the source field. The interpreter field defines the scripting language.
- `postgres`: Executes a PostgreSQL database query. The sql field defines the SQL query.

If the `type` field is not explicitly defined and the template contains a `steps` or `tasks` field, it means the template describes a workflow:

- `steps`: Templates under this field will be executed sequentially.
- `tasks`: Templates under this field will be executed in parallel.

The `initialTemplate` field in the `spec` section defines which template to execute first when the workflow starts. This can be overridden from the command line.

The NoETL Workflow configuration provides a robust framework for defining complex workflows. It is flexible enough to encapsulate different types of operations and workflows, and is easy to understand and use. By carefully structuring your configuration file and validating it, you can ensure your workflows are executed smoothly and effectively.
