apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: noetl-platform
  labels:
    grafana_datasource: "1"
data:
  victoriametrics.yaml: |
    apiVersion: 1
    datasources:
      - name: VictoriaMetrics
        type: prometheus
        url: http://vmsingle-vmstack-victoria-metrics-k8s-stack.noetl-platform.svc.cluster.local:8428
        access: proxy
        isDefault: true
        jsonData:
          timeInterval: "30s"
          queryTimeout: "60s"
          httpMethod: POST
      - name: VictoriaLogs
        type: victorialogs-datasource
        url: http://vlogs-victoria-logs-single-server.noetl-platform.svc.cluster.local:9428
        access: proxy
        isDefault: false
        jsonData:
          maxLines: 1000