apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: noetl-workers
  namespace: observability
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: noetl-worker
  podMetricsEndpoints:
    - port: http-metrics
      path: /metrics
      interval: 15s
