apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: noetl-server
  namespace: observability
spec:
  namespaceSelector:
    matchNames:
      - noetl
  selector:
    matchLabels:
      app: noetl
  podMetricsEndpoints:
    - path: /metrics
      interval: 15s
      scheme: http
      port: metrics  # Use named port instead of targetPort
      targetPort: 8082
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: noetl-workers
  namespace: observability
spec:
  namespaceSelector:
    matchNames:
      - noetl
  selector:
    matchLabels:
      app: noetl-worker
  podMetricsEndpoints:
    - path: /metrics
      interval: 15s
      scheme: http
      port: metrics  # Use named port
      targetPort: 8082  # Adjust if workers use different port
