---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres
  namespace: postgres
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /mnt/data/pg-data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres
  namespace: postgres
spec:
  volumeName: postgres
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
