
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: postgres
  labels:
    app: postgres
type: Opaque
data:
  POSTGRES_PASSWORD: ZGVtbw==  # 'demo' encoded in base64
  NOETL_PASSWORD: bm9ldGw=     # 'noetl' encoded in base64
