apiVersion: v1
kind: Service
metadata:
  name: postgres-ext
  namespace: postgres
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
    - port: 5432
      nodePort: 30321
      protocol: TCP
      name: postgres
  selector:
    app: postgres
