import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * NoETL Documentation Sidebars
 * 
 * Structure:
 * - Getting Started (intro, quickstart)
 * - DSL Guide (playbook structure, workflow patterns)
 * - Reference (DSL spec, CLI, tools, observability)
 * - Features (pagination, retry, caching, variables)
 * - Examples (authentication, data transfer, integrations)
 * - Operations (deployment, monitoring, troubleshooting)
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'getting-started/quickstart',
        'getting-started/installation',
        'getting-started/architecture',
        'getting-started/message-learning',
        'getting-started/design-philosophy',
        'getting-started/semantic-pipeline',
      ],
    },
    {
      type: 'category',
      label: 'Playbook Guide',
      items: [
        {
          type: 'doc',
          id: 'features/playbook_structure',
          label: 'Playbook Structure',
        },
        {
          type: 'doc',
          id: 'features/core_concept',
          label: 'Core Concepts',
        },
        {
          type: 'doc',
          id: 'features/variables',
          label: 'Variables',
        },
        {
          type: 'doc',
          id: 'features/iterator',
          label: 'Iterator (Loops)',
        },
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        {
          type: 'category',
          label: 'DSL',
          link: {
            type: 'doc',
            id: 'reference/dsl/index',
          },
          items: [
            'reference/dsl/dsl_spec',
            'reference/dsl/variables_feature_design',
            'reference/dsl/vars_block_quick_reference',
            'reference/dsl/vars_block_implementation_summary',
            'reference/dsl/unified_retry',
            'reference/dsl/http_pagination_quick_reference',
          ],
        },
        {
          type: 'doc',
          id: 'reference/noetl_cli_usage',
          label: 'CLI Reference',
        },
        {
          type: 'category',
          label: 'Tools',
          link: {
            type: 'doc',
            id: 'reference/tools/index',
          },
          items: [
            'reference/tools/http',
            'reference/tools/postgres',
            'reference/tools/python',
            'reference/tools/duckdb',
            'reference/tools/snowflake',
            'reference/tools/container',
            'reference/tools/gcs',
            'reference/tools/ducklake',
            'reference/tools/transfer',
          ],
        },
        {
          type: 'doc',
          id: 'reference/http_action_type',
          label: 'HTTP Action Details',
        },
        {
          type: 'doc',
          id: 'reference/auth_and_keychain_reference',
          label: 'Authentication & Keychain',
        },
        {
          type: 'doc',
          id: 'reference/observability_services',
          label: 'Observability',
        },
      ],
    },
    {
      type: 'category',
      label: 'Advanced Features',
      items: [
        'features/pagination',
        'features/retry_mechanism',
        'features/credential_caching',
        'features/nats_kv_distributed_cache',
        'features/script_tool',
        'features/script_attribute',
      ],
    },
    {
      type: 'category',
      label: 'Operations',
      items: [
        {
          type: 'autogenerated',
          dirName: 'operations',
        },
      ],
    },
    {
      type: 'category',
      label: 'Development',
      items: [
        {
          type: 'autogenerated',
          dirName: 'development',
        },
      ],
    },
  ],
  examplesSidebar: [
    {
      type: 'category',
      label: 'Examples',
      items: [
        {
          type: 'autogenerated',
          dirName: 'examples',
        },
      ],
    },
  ],
};

export default sidebars;
