import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * NoETL Documentation Sidebars
 *
 * Structure:
 * - Getting Started (intro, quickstart)
 * - DSL Guide (playbook structure, workflow patterns)
 * - Reference (DSL spec, CLI, tools, observability)
 * - Features (pagination, retry, caching, variables)
 * - Examples (authentication, data transfer, integrations)
 * - Operations (deployment, monitoring, troubleshooting)
 * - Gateway (auth integration, async callbacks, deployment)
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'getting-started/quickstart',
        'getting-started/installation',
        'getting-started/architecture',
        'getting-started/message-learning',
        'getting-started/design-philosophy',
        'getting-started/semantic-pipeline',
        'architecture/sink_driven_storage',
      ],
    },
    {
      type: 'category',
      label: 'Playbook Guide',
      items: [
        {
          type: 'doc',
          id: 'reference/dsl/playbook_structure',
          label: 'Playbook Structure',
        },
        'features/infrastructure_as_playbook',
        {
          type: 'doc',
          id: 'reference/core_concept',
          label: 'Core Concepts',
        },
        {
          type: 'doc',
          id: 'reference/variables',
          label: 'Variables',
        },
        {
          type: 'doc',
          id: 'reference/iterator',
          label: 'Iterator (Loops)',
        },
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        {
          type: 'category',
          label: 'DSL',
          link: {
            type: 'doc',
            id: 'reference/dsl/index',
          },
          items: [
            'reference/dsl/spec',
            'reference/dsl/playbook_structure',
            'reference/dsl/mental_model',
            'reference/dsl/execution_model',
            'reference/dsl/formal_specification',
            'reference/dsl/runtime_events',
            'reference/dsl/runtime_results',
            'reference/dsl/pagination',
            'reference/dsl/dsl_specification',
            'reference/dsl/step_spec',
            'reference/dsl/dsl_analysis_and_evaluation',
            'reference/dsl/workflow_patterns_comparison',
          ],
        },
        {
          type: 'doc',
          id: 'reference/noetl_cli_usage',
          label: 'CLI Reference',
        },
        {
          type: 'category',
          label: 'noetlctl CLI',
          items: [
            {
              type: 'autogenerated',
              dirName: 'noetlctl',
            },
          ],
        },
        {
          type: 'category',
          label: 'Tools',
          link: {
            type: 'doc',
            id: 'reference/tools/index',
          },
          items: [
            'reference/tools/http',
            'reference/tools/postgres',
            'reference/tools/python',
            'reference/tools/duckdb',
            'reference/tools/snowflake',
            'reference/tools/container',
            'reference/tools/gcs',
            'reference/tools/ducklake',
            'reference/tools/transfer',
          ],
        },
        {
          type: 'doc',
          id: 'reference/http_action_type',
          label: 'HTTP Action Details',
        },
        {
          type: 'doc',
          id: 'reference/auth_and_keychain_reference',
          label: 'Authentication & Keychain',
        },
        {
          type: 'doc',
          id: 'reference/observability_services',
          label: 'Observability',
        },
      ],
    },
    {
      type: 'category',
      label: 'Advanced Features',
      items: [
        'reference/pagination',
        'reference/retry_mechanism',
        'reference/credential_caching',
        'features/nats_kv_distributed_cache',
        'reference/script_execution',
        'features/worker-pool-rust',
        {
          type: 'category',
          label: 'Infrastructure as Playbook',
          items: [
            'features/iap_gcs_bucket_structure',
            'features/iap_development_plan',
            'features/iap_gcp_autopilot_deploy',
            'features/gke_autopilot_full_provisioning',
            'features/gke_autopilot_service_protection',
          ],
        },
        {
          type: 'category',
          label: 'Feature Tools',
          items: [
            'features/tools/script',
            'features/tools/snowflake',
            'features/tools/transfer',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Operations',
      items: [
        {
          type: 'autogenerated',
          dirName: 'operations',
        },
      ],
    },
    {
      type: 'category',
      label: 'Gateway',
      link: {
        type: 'doc',
        id: 'gateway/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'gateway',
        },
      ],
    },
    {
      type: 'category',
      label: 'IAP GCP',
      items: [
        {
          type: 'autogenerated',
          dirName: 'iap-gcp',
        },
      ],
    },
    {
      type: 'category',
      label: 'Testing',
      items: [
        {
          type: 'autogenerated',
          dirName: 'test',
        },
      ],
    },
    {
      type: 'category',
      label: 'Development',
      items: [
        {
          type: 'autogenerated',
          dirName: 'development',
        },
      ],
    },
    {
      type: 'category',
      label: 'Contributing',
      items: [
        {
          type: 'autogenerated',
          dirName: 'contributing',
        },
      ],
    },
    {
      type: 'category',
      label: 'Release Notes',
      items: [
        {
          type: 'autogenerated',
          dirName: 'release',
        },
      ],
    },
  ],
  examplesSidebar: [
    {
      type: 'category',
      label: 'Examples',
      items: [
        {
          type: 'autogenerated',
          dirName: 'examples',
        },
      ],
    },
  ],
};

export default sidebars;
